// fig-bubble.mjs <arm> <theme> — compose via the real picker, send, crop the user bubble live and after refresh.
import { launch, UI_URL, OUT, sleep, userTags, save } from './ui.mjs';
const [arm, theme] = process.argv.slice(2);
const { browser, context, page, log } = await launch({ width: 1100, height: 700 });
await context.addInitScript((t) => { try { localStorage.setItem('qwen-code-web-shell-theme', t); } catch {} }, theme);
await page.goto(UI_URL); await sleep(4000);
await page.getByText('New task').first().click(); await sleep(1200);
const ed = page.locator('[contenteditable="true"]').first(); await ed.click();
const pick = async (prov, ...path) => { await page.keyboard.type('@'); await sleep(700);
  await page.locator('[role="option"]', { hasText: prov }).first().click(); await sleep(1100);
  for (const p of path) { await page.locator('[role="option"]', { hasText: p }).first().click(); await sleep(1000); } };
await page.keyboard.type('Review ');
await pick('Files', 'README.md'); await page.keyboard.type('using ');
await pick('Extensions', 'browser-kit'); await page.keyboard.type('and ');
await pick('MCP resources', 'o2-docs');
await page.keyboard.press('Enter');
await page.getByText('Done. (mock reply)').first().waitFor({ timeout: 30000 }); await sleep(2000);
const bubble = () => page.locator('[class*="chatBubble"]').first();
await page.mouse.move(5, 5); await sleep(300);
const toastSel = await page.evaluate(() => { const el = [...document.querySelectorAll('*')].find((e) => e.children.length < 6 && /not found for authType/.test(e.textContent || '') && getComputedStyle(e).position.match(/fixed|absolute/)); if (el) { el.style.display = 'none'; return el.className; } return null; });
console.log('hid toast:', toastSel);
await page.addStyleTag({ content: '[class*="toast" i], [class*="Toast"] { display: none !important; }' }); await sleep(300);
await bubble().screenshot({ path: `${OUT}/fig-${arm}-${theme}-live.png` });
const live = await userTags(page);
await page.reload(); await sleep(6000); await page.mouse.move(5, 5); await sleep(300);
await bubble().screenshot({ path: `${OUT}/fig-${arm}-${theme}-refresh.png` });
const refresh = await userTags(page);
console.log(`[${arm}/${theme}] live:`, JSON.stringify(live.map((t) => `${t.text} h${t.h} r${t.radius} pr${t.padR} ${t.font}`)), '\n   refresh tags:', refresh.length);
save(`fig-${arm}-${theme}.json`, { live, refresh, url: page.url() });
await browser.close();
