// s7-queued.mjs <arm> — tags inside a queued prompt (QueuedPromptDisplay reuses ReadonlyComposerTag).
import { launch, UI_URL, OUT, sleep } from './ui.mjs';
const arm = process.argv[2];
const { browser, context, page } = await launch({ width: 1100, height: 760 });
let posts = 0; page.on('request', (r) => { if (r.method() === 'POST' && /\/prompt$/.test(r.url())) posts++; });
await context.addInitScript(() => { try { localStorage.setItem('qwen-code-web-shell-theme', 'light'); } catch {} });
await page.goto(UI_URL); await sleep(4000);
await page.getByText('New task').first().click(); await sleep(1200);
const ed = page.locator('[contenteditable="true"]').first(); await ed.click();
await page.keyboard.type('SLOWTURN warm up'); await page.keyboard.press('Enter'); await sleep(2500);
await ed.click();
const pick = async (prov, item) => { await page.keyboard.type('@'); await sleep(700);
  await page.locator('[role="option"]', { hasText: prov }).first().click(); await sleep(1100);
  await page.locator('[role="option"]', { hasText: item }).first().click(); await sleep(900); };
await page.keyboard.type('Queued ');
await pick('Files', 'README.md'); await page.keyboard.type('with ');
await pick('Extensions', 'browser-kit'); await page.keyboard.type('and ');
await pick('MCP resources', 'o2-docs');
await page.keyboard.press('Enter'); await sleep(1500);
console.log(`[${arm}] still processing:`, await page.getByText(/Processing|esc to cancel/).count(), ' prompt POSTs so far:', posts);
await page.addStyleTag({ content: '[class*="toast" i] { display: none !important; }' });
const q = page.locator('[class*="queued" i]', { hasText: 'Queued' }).first();
console.log(`[${arm}] queued container found:`, await q.count());
const tags = await page.locator('[class*="queued" i] [class*="messageTag"][title]').evaluateAll((els) => els.map((e) => { const cs = getComputedStyle(e); const r = e.getBoundingClientRect(); return `${e.textContent.trim()} h${Math.round(r.height)} r${cs.borderRadius} pr${cs.paddingRight} ${cs.fontFamily.split(',')[0]}`; }));
console.log(`[${arm}] queued tags:`, JSON.stringify(tags));
await page.screenshot({ path: `${OUT}/${arm}-s7-queued.png` });
if (await q.count()) await q.screenshot({ path: `${OUT}/fig-${arm}-queued.png` });
await page.waitForFunction(() => document.body.innerText.split('Done. (mock reply)').length - 1 >= 2, null, { timeout: 90000 });
await sleep(2500);
const drained = await page.locator('[class*="chatBubble"]', { hasText: 'Queued' }).first().locator('[class*="messageTag"][title]').count();
await page.reload(); await sleep(6000);
const reloaded = await page.locator('[class*="chatBubble"]', { hasText: 'Queued' }).first().locator('[class*="messageTag"][title]').count();
console.log(`[${arm}] queued prompt after it ran: tags live=${drained} after reload=${reloaded}`);
await browser.close();
