// Card spec for PR #13090 verification figures (English only; Chinese lives in the comment body).
import fs from 'node:fs';
const S5 = JSON.parse(fs.readFileSync(new URL('./s5.json', import.meta.url), 'utf8'));
const cards = [
{
  name: '01-gates-head',
  title: 'PR #13090 @ d41914ff — deployment gates run locally (two-stage: Maven && report checker)',
  subtitle: 'macOS 26 arm64 · Zulu JDK 21.0.12 · Maven 3.9.16 · dedicated MySQL 8.4.7 (UTC) · JVM TZ Asia/Shanghai · real Aliyun OSS cn-hangzhou (temporary private bucket, deleted afterwards)',
  lines: [
    '## Default backend gate: mvn clean verify checkstyle:check',
    '++ Tests run: 404, Failures: 0, Errors: 0, Skipped: 0          Checkstyle violations: 0          (73 s)',
    '',
    '## -P o4-mysql-gates  (runbook command, qwen_o4_ base URL, password via QWEN_O4_MYSQL_PASSWORD)',
    '++ run 1: surefire 404/404 + failsafe O4MySqlGate 35/35, 0 skipped · maven exit 0 · checker exit 0 → PASS (233 s)',
    '++ run 2: surefire 404/404 + failsafe O4MySqlGate 35/35, 0 skipped · maven exit 0 · checker exit 0 → PASS (243 s)',
    '== stoppedProcessResumesAfterRealLeaseDeadlineWithoutReturningBytes  123.2 s (real 2-minute lease, SIGSTOP/SIGCONT)',
    '== largeCatalogCollectionUsesBoundedPages 100 MiB 1.7 s · 1 GiB 5.6 s (filesystem adapter)',
    '== every generated qwen_o4_* schema dropped afterwards (only the supplied qwen_o4_gate remains)',
    '',
    '## -P o4-oss-gates  (real OSS; ONLY ONE identity available → OSS_DELETE_DENIED_* = the normal identity)',
    '++ realDeleteLostResponseRetriesAndConfirmsMissingObject                     1.9 s   pass',
    '++ largeCatalogCollectionUsesBoundedPages(100 MiB)  real OSS PUT + read-back + delete   41.4 s   pass',
    '++ largeCatalogCollectionUsesBoundedPages(1 GiB)    real OSS PUT + read-back + delete  430.7 s   pass',
    '++ 33 inherited real-MySQL/process cases                                              pass',
    '-- realPermissionFailurePreservesQuotaUntilAuthorizedRetry   FAIL  "Expecting code to raise a throwable" (O4OssGate.java:110)',
    '!!    expected: the "denied" client is the same identity, so its DeleteObject succeeds — the case is identity-sensitive',
    '== 36/37 · maven exit 1 · checker exit 1 → FAIL (707 s) · bucket held 0 objects after teardown, then deleted (NoSuchBucket)',
  ],
  note: 'Everything that could run passed. The delete-denied case is NOT executed evidence: the maintainer key is a RAM user without ram:CreateUser, so no second identity could be created; nothing was created in RAM.',
  noteColor: '#3fb950',
},
{
  name: '02-saturation-ab',
  title: 'Carry-forward #2 on the real stack: 150 grace-held publications in front of one eligible publication',
  subtitle: 'Same snapshot for both arms: 151 publications from real Hosted Harness → Broker worker Shell calls (MySQL 8.4.7, TLS fake OSS). Grace 120 s. E retired at t0, B (150) at t0+64 s.',
  lines: [
    '## arm                          E eligible   E collected   delay after eligible   held rows re-evaluated (per minute)',
    '-- base O4-2 6ff843bc  LIMIT 1     +120.9 s      +215.7 s           94,789 ms        {"0":1,"1":58,"2":59,"3":2}  total 120',
    '++ head O4-3 d41914ff  LIMIT 32    +120.9 s      +121.1 s              173 ms        {"0":1,"1":150}              total 151',
    '',
    '== base re-evaluates one held row per tick (58-59/min cap) and pushes it to now+60 s, so E waits behind the queue',
    '== head evaluates up to 32 per tick and parks each grace row at retired_at + grace: one evaluation per row',
    '== (O4-2 review measured 95.2 s on its own rig; this rig reproduces it at 94.8 s before the fix)',
    '',
    '## end of 330 s window: B collected 143 (head) / 144 (base); per-row check: 0 rows collected before retired_at + grace',
  ],
  note: 'The held-candidate gate carried from #13087 is fixed for grace-held rows: 94.8 s → 0.17 s on identical inputs.',
  noteColor: '#3fb950',
},
{
  name: '03-legacy-backlog',
  title: 'New: permanently blocked rows still cost one 60-second poll each — capacity is 32 rows/s per instance',
  subtitle: 'V27 adds write_evidence BOOLEAN NOT NULL DEFAULT FALSE, so every pre-upgrade publication in a deleted Session is legacy_write_evidence_missing forever. 150 real rows marked legacy + SQL clones; grace 120 s; E retired at +200 s.',
  lines: S5.lines,
  note: S5.note,
  noteColor: '#d29922',
},
{
  name: '04-expiry-grace',
  title: 'Claim expiry mid-page and grace changes on the real stack (head d41914ff vs base 6ff843bc)',
  subtitle: 'E = 7 OSS + 5 inline objects in one page; B1 = 50 healthy publications retired while the collector is busy; grace 0 s unless stated',
  lines: [
    '## S3  JVM frozen 65 s (SIGSTOP) while E\'s first DELETE is in flight',
    '== both arms identical: the OSS SDK 50 s socket timeout fires on resume → existing catch → defer (collection_retry, +60 s)',
    '== → the new line is not reached this way; first B1 collected +1.2 s after SIGCONT in both arms',
    '',
    '## S3b renew SQL held 65 s at a MySQL proxy (claim expires BETWEEN objects; OSS never slow)',
    '++ head: zero-row renew at +68.3 s → NEW defer → collection_retry, next +60 s · B1 50/50 first · E COLLECTED gen 2 at +128.9 s',
    '== base: zero-row renew at +68.3 s → return false (no defer) · B1 50/50 first (row order) · E COLLECTED gen 2 at +121.3 s',
    '== both: 9 DELETEs for 7 keys (2 repeats → 204-missing), quota released once (6,309,504 B)',
    '!! pre-existing: the held renew still matched (its "now" was read before the stall), so one more key was deleted after expiry',
    '',
    '## S4  grace 600 s → E evaluated → restart with grace 30 s',
    '-- head: gc_next_at = retired_at + 600 s; still RETIRING 165 s later (next check in 436 s)',
    '== base: gc_next_at = now + 60 s; COLLECTED 61 s after retirement',
  ],
  note: 'Expiry handling is safe on real processes (exact keys, single release). A shortened grace no longer applies to rows already evaluated until their old deadline — conservative, but undocumented.',
  noteColor: '#d29922',
},
{
  name: '05-landing',
  title: 'Landing: this PR cannot reach main through its current base',
  subtitle: 'base codex/managed-tool-result-o4-2 = #13087, CLOSED 2026-10-02T05:49:48Z (20 s after O4-1 #13084 merged). origin/main d5c22d33.',
  lines: [
    '## merge PR head into main (trial)',
    '-- 16 conflicted files (7 AA, 9 UU) + duplicate Flyway versions:',
    '--   V27__managed_hook_records.sql        vs V27__managed_tool_output_retention.sql',
    '--   V28__managed_hook_admission_index.sql vs V28__managed_tool_output_collection.sql   (O4-1 already landed as V30)',
    '',
    '## replay O4-2 + O4-3 commits onto main (git cherry-pick 9f5e66f2a3..d41914ff3b)',
    '++ 9 commits, 1 trivial conflict (ToolPublicationObjectStore: keep both default methods)',
    '-- scripts/check-flyway-migrations.js: "2 migrations claim version 28" → exit 1',
    '++ rename V28__managed_tool_output_collection → V31: "31 migrations, all versions unique" → exit 0',
    '++ default gate on this candidate 38fcb7bd: Tests run 455, Failures 0, Errors 0, Skipped 0 · Checkstyle 0',
    '++ ' + S5.landing,
    '== collector, configuration, O4 gates, collector test, report checker: byte-identical to d41914ff',
    '',
    '## PR CI: only administrative checks ran (stacked base); no SDK Java / product jobs',
  ],
  note: 'Code is ready to re-land, but merging #13090 as-is would land it on a closed PR\'s branch. Re-target main (new PR) with the collection migration at V31.',
  noteColor: '#f85149',
},
{
  name: '06-mutation-checker',
  title: 'Mutation and report-checker probes',
  subtitle: 'Java mutants on ToolPublicationCollector (default suite, survivors re-judged on the real-MySQL O4 gate); checker mutants judged by scripts/tests/check-failsafe-reports.test.js',
  lines: [
    '## Java (12 mutants): 9 killed by the default suite',
    '++ J1 LIMIT 32→1 · J2 grace next=now+60s · J3 next=retired_at · J4 next=now+grace · J10 LIMIT 4 · J12 LIMIT 1000',
    '++ J5 no defer after claim loss · J6 always probe (inline-only too) · J9 claim every candidate',
    '== J11 LIMIT 31: survives (boundary, behaviourally equivalent for the 150+1 fixture)',
    '== J7 no page probe / J8 anyMatch→allMatch: survive unit AND O4 MySQL (35/35) — adapter probes before every key',
    '!! J7 first looked killed by ignoresLateEnvironmentResultFromAnOlderTurn (known flake); rerun: survives',
    '',
    '## report checker (10/10 tests pass): 5/6 mutants killed',
    '-- C3 reject only <skipped>, not <failure>/<error>: SURVIVES the 10 tests',
    '!!    real run: J5 + -Dmaven.test.failure.ignore=true → Maven exit 0; real checker exit 1;',
    '!!    C3 checker on the same report (1 <failure>) exit 0 → a failing gate would pass both stages',
    '',
    '## selector probes on the real O4 MySQL profile',
    '++ -Dit.test=O4MySqlGate#writerReally…  maven exit 0 (1 test) · checker: "narrowed this run" → FAIL',
    '++ -Dit.test=O4MySqlGate#noSuchMethod    maven exit 0 ("No tests to run.") · checker: "ran no test" → FAIL',
  ],
  note: 'The two-stage entry is necessary as the runbook says: Maven alone accepted both an empty and a narrowed selector.',
  noteColor: '#3fb950',
},
];
fs.writeFileSync(new URL('./cards.json', import.meta.url), JSON.stringify(cards, null, 1));
console.log('cards', cards.length);
