export default {
 "R2_CLASS": {
  "M04": "equivalent: an install always bumps the epoch, so the epoch conjunct already rejects a fresh activation",
  "M26": "unreachable after the round-2 restructure: a blocked pump takes the poll branch for an expired lease, and an unblocked pump arms this wake only when nothing is runnable",
  "M32": "equivalent: the release outcome is a string union, so the clone cannot be observed (AutoFix round 2 is right; round 1 called it a gap)"
 },
 "R2_NOTE3": "47/50 reverts are caught, every kill by a test that is not one of the known timing flakes. The three survivors are equivalent or unreachable. Round 1's F1 and F2 rows landed (M18, M19, M28, M29 are now killed), and every new round-2 guard (N01–N17) has a witness, including the chunked-body read: be6fb30d added no test, but two existing chunking tests (HTTP store oversized message, projection past the inline limit) kill its revert.",
 "R2_MERGE_HTML": "<h2>Merging into current main: 16 of main's new tests fail deterministically on the merge tree (they pass on main and on head)</h2>\n<table><tr><th>test (added on main after head's last main merge)</th><th>merge</th><th>main</th><th>cause</th><th>verified candidate fix</th></tr>\n<tr><td class=\"mono\">core http-managed-session-store.test.ts › treats the verdict/mint gate refusal as rollbackable… (#13550)</td><td class=\"mono bad\">fails</td><td class=\"mono ok\">passes</td><td class=\"mono\">fixture publishes a bare {\"role\":\"user\",…} message body; the new message.committed fence refuses it before the 409 gate</td><td class=\"mono ok\">use the file's MESSAGE_BODY → 74/74</td></tr>\n<tr><td class=\"mono\">cli hosted-channel-session.test.ts › 15 \"HostedChannelSession outbound …\" tests (#13572)</td><td class=\"mono bad\">15 fail</td><td class=\"mono ok\">20/20</td><td class=\"mono\">settleInJournal() commits turn.settled with resultRef: null; the fence refuses a null result ref</td><td class=\"mono ok\">publish a reader-facing turn_result and pass its ref → 20/20</td></tr></table>\n<p class=\"dim\" style=\"font-size:12.5px\">Production is not affected: the only production turn.settled writers (the record sink, commitTurnComplete) always carry a published result, and the only production message.committed writer is the sink's projection of reader-facing records.</p>\n<h2>Whole-directory suites (the remaining merge-only failures are load noise: different tests fail on each run and on main too)</h2>\n<table><tr><th>tree</th><th>suites</th><th>result</th><th>failures</th></tr><tr><td class=\"mono\">trial merge (head + main f20ed558)</td><td class=\"mono\">core src/managed-runtime + src/services + managed-session-log</td><td class=\"mono\">135 files, 6519/6523 pass</td><td class=\"mono\">4 failed</td></tr><tr><td class=\"mono\">trial merge (head + main f20ed558)</td><td class=\"mono\">cli src/serve</td><td class=\"mono\">310 files, 13568/13600 pass</td><td class=\"mono\">32 failed</td></tr><tr><td class=\"mono\">main f20ed558</td><td class=\"mono\">core src/managed-runtime + src/services + managed-session-log</td><td class=\"mono\">135 files, 6461/6464 pass</td><td class=\"mono\">3 failed</td></tr><tr><td class=\"mono\">main f20ed558</td><td class=\"mono\">cli src/serve</td><td class=\"mono\">310 files, 13581/13601 pass</td><td class=\"mono\">20 failed</td></tr></table>",
 "R2_NOTE4": "No regression end to end. Every --session-failover failure on both arms is the runner's 1 s Session Store writer grant lapsing under host load 44–68; in a quiet window both arms were 6/6. Every real-model run whose Spring server started completed its turn on head and merge."
};
