// Generate pre-fix / post-fix probe copies of hosted-harness-session.test.ts.
// Probe: inside the 'settles a turn after one %s failure' test only, arm a
// one-shot 1.2s delay on the next durable journal append after each prompt
// admission — simulating a contended CI runner where the settlement retry's
// fsynced writes outlast vitest's default 1s waitFor window. NOT part of the PR.
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const WT = '/root/git/qwen-code-pr13058';
const REL = 'packages/cli/src/serve/hosted-harness-session.test.ts';
const HEAD = 'bf0c3a3fe14b7a599a21bbd8ded807ba80ccc5cd';

const postfix = fs.readFileSync(`${WT}/${REL}`, 'utf8');
const prefix = execFileSync('git', ['-C', WT, 'show', `${HEAD}^:${REL}`], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

const probeBlock = `
      // PROBE ONLY (not part of the PR): simulate a contended CI runner by
      // delaying the next durable journal append by 1.2s, so the settlement
      // retry's terminal event lands outside vitest's default 1s waitFor
      // window. Reverted after the probe runs.
      {
        const probeAppend =
          LocalJsonlManagedSessionJournalHandle.prototype.appendTransaction;
        let probeArmed = true;
        vi.spyOn(
          LocalJsonlManagedSessionJournalHandle.prototype,
          'appendTransaction',
        ).mockImplementation(function (
          this: LocalJsonlManagedSessionJournalHandle,
          ...args: Parameters<
            LocalJsonlManagedSessionJournalHandle['appendTransaction']
          >
        ) {
          if (probeArmed) {
            probeArmed = false;
            return new Promise((resolve, reject) => {
              setTimeout(() => {
                probeAppend.apply(this, args).then(resolve, reject);
              }, 1_200);
            });
          }
          return probeAppend.apply(this, args);
        });
      }`;

const anchors = [
  `      const admitted = await send();
      expect(admitted.status).toBe(202);`,
  `      expect(next.status).toBe(202);`,
];

const inject = (src) => {
  let out = src;
  for (const a of anchors) {
    if (!out.includes(a)) throw new Error(`anchor not found: ${a.slice(0, 50)}`);
    out = out.replace(a, a + probeBlock);
  }
  const imp = `import { LocalJsonlManagedSessionJournalStore } from`;
  if (!out.includes(imp)) throw new Error('import anchor not found');
  out = out.replace(imp, `import { LocalJsonlManagedSessionJournalHandle, LocalJsonlManagedSessionJournalStore } from`);
  return out;
};

const banner = (v) => `// PROBE COPY (${v}) of hosted-harness-session.test.ts — generated by /root/rig13058/gen-probes.mjs, not part of PR #13058.\n`;
fs.writeFileSync(`${WT}/packages/cli/src/serve/hosted-harness-session-probe-prefix.test.ts`, banner('pre-fix') + inject(prefix));
fs.writeFileSync(`${WT}/packages/cli/src/serve/hosted-harness-session-probe-postfix.test.ts`, banner('post-fix') + inject(postfix));
console.log('prefix target-test 10s timeouts:', (prefix.match(/timeout: 10_000/g) || []).length, '(siblings only)');
console.log('postfix 10s timeouts:', (postfix.match(/timeout: 10_000/g) || []).length);
console.log('probe files written (one-shot journal-append delay design)');
