// One mutant per condition of ManagedExtensionRecords.requireChildRun /
// isChildRunStart / isChildRunSuccessor (PR #13265 head). Each `find` must
// occur exactly once in the file.
export const FILE = 'packages/sdk-java/managed-agent-server/src/main/java/com/alibaba/qwen/code/managedagent/store/ManagedExtensionRecords.java';
export const MUTANTS = [
  ['J01 kind check dropped', `require("shell".equals(child.get("kind").textValue()),`, `require(true || "shell".equals(child.get("kind").textValue()),`],
  ['J02 start call may be absent', `require(!run.get("executionCallId").isNull()\n                && run.get("effectId").isNull()`, `require(run.get("effectId").isNull()`],
  ['J03 effectId allowed', `&& run.get("effectId").isNull()\n                && run.get("dispatchId").isNull()`, `&& run.get("dispatchId").isNull()`],
  ['J04 dispatchId allowed', `&& run.get("dispatchId").isNull()\n                && run.get("deliveryId").isNull()\n                && run.get("delivery").isNull()\n                && run.get("definition").isNull(),\n                "childRun`, `&& run.get("deliveryId").isNull()\n                && run.get("delivery").isNull()\n                && run.get("definition").isNull(),\n                "childRun`],
  ['J05 delivery allowed', `&& run.get("delivery").isNull()\n                && run.get("definition").isNull(),\n                "childRun`, `&& run.get("definition").isNull(),\n                "childRun`],
  ['J06 definition allowed', `&& run.get("definition").isNull(),\n                "childRun.run must name`, `,\n                "childRun.run must name`],
  ['J07 receipt before start allowed', `require(startReceipt.isNull() || execution != null\n                && !"intent".equals(execution)`, `require(true || execution != null\n                && !"intent".equals(execution)`],
  ['J08 attached without receipt', `|| !"running_attached".equals(execution)\n                        && !"settled".equals(execution),`, `|| !"settled".equals(execution),`],
  ['J09 settled execution without receipt', `|| !"running_attached".equals(execution)\n                        && !"settled".equals(execution),`, `|| !"running_attached".equals(execution),`],
  ['J10 receipt without runtime', `require(startReceipt.isNull() || !run.get("runtime").isNull(),`, `require(true,`],
  ['J11 output kind unchecked', `require(MONITOR_OUTPUT_KIND.equals(output.get("kind").textValue())\n                    && output.get("schemaVersion").asLong() == 1,\n                    "childRun`, `require(output.get("schemaVersion").asLong() == 1,\n                    "childRun`],
  ['J12 output version unchecked', `&& output.get("schemaVersion").asLong() == 1,\n                    "childRun`, `,\n                    "childRun`],
  ['J13 output without receipt', `require(output.isNull() || !startReceipt.isNull(),\n                "childRun.outputRef needs`, `require(true,\n                "childRun.outputRef needs`],
  ['J15 exitCode 256 allowed', `count(exitCode, 0, 255, "childRun.exitCode");`, `count(exitCode, 0, 256, "childRun.exitCode");`],
  ['J16 negative exitCode allowed', `count(exitCode, 0, 255, "childRun.exitCode");`, `count(exitCode, -1, 255, "childRun.exitCode");`],
  ['J18 16-char signal limit +1', `"[A-Z][A-Z0-9]{0,15}"`, `"[A-Z][A-Z0-9]{0,16}"`],
  ['J19 lowercase signal allowed', `"[A-Z][A-Z0-9]{0,15}"`, `"[A-Za-z][A-Za-z0-9]{0,15}"`],
  ['J20 stopReason iff terminal dropped', `require((stopReason == null) != TERMINAL.contains(state),\n                "childRun`, `require(true,\n                "childRun`],
  ['J21 stopReason fits state dropped', `|| CHILD_STOP_REASONS.get(state).contains(stopReason),`, `|| true,`],
  ['J22 settled without settled execution', `require(!"settled".equals(state) || "settled".equals(execution)\n                && !startReceipt.isNull(),`, `require(!"settled".equals(state) || !startReceipt.isNull(),`],
  ['J23 settled without receipt', `require(!"settled".equals(state) || "settled".equals(execution)\n                && !startReceipt.isNull(),`, `require(!"settled".equals(state) || "settled".equals(execution),`],
  ['J24 start_failed with receipt', `|| startReceipt.isNull() && execution != null,`, `|| execution != null,`],
  ['J25 start_failed never attempted', `|| startReceipt.isNull() && execution != null,`, `|| startReceipt.isNull(),`],
  ['J26 process_failed without receipt', `require(!"process_failed".equals(stopReason) || !startReceipt.isNull(),`, `require(true,`],
  ['J27 quota iff quota reason dropped', `require("quota_exceeded".equals(stopReason)\n                == (reason != null && QUOTA_REASONS.contains(reason)),`, `require(true,`],
  ['J28 evidence on non-exit allowed', `: exitCode.isNull() && exitSignal.isNull(),`, `: true,`],
  ['J29 exit without evidence allowed', `? !exitCode.isNull() || !exitSignal.isNull()\n                : exitCode`, `? true\n                : exitCode`],
  ['J30 start may carry output', `&& isRunStart(child.get("run"))\n                && child.get("outputRef").isNull();`, `&& isRunStart(child.get("run"));`],
  ['J31 commandRef may change', `private static final List<String> CHILD_FIXED = List.of("kind", "shellId",\n            "ownerScopeId", "commandRef");`, `private static final List<String> CHILD_FIXED = List.of("kind", "shellId",\n            "ownerScopeId");`],
  ['J32 ownerScopeId may change', `private static final List<String> CHILD_FIXED = List.of("kind", "shellId",\n            "ownerScopeId", "commandRef");`, `private static final List<String> CHILD_FIXED = List.of("kind", "shellId",\n            "commandRef");`],
  ['J33 shellId may change', `private static final List<String> CHILD_FIXED = List.of("kind", "shellId",\n            "ownerScopeId", "commandRef");`, `private static final List<String> CHILD_FIXED = List.of("kind",\n            "ownerScopeId", "commandRef");`],
  ['J34 run successor unchecked', `if (!isRunSuccessor(previous.get("run"), next.get("run"))\n                || !previous.get("outputRef").isNull()`, `if (!previous.get("outputRef").isNull()`],
  ['J35 output may be removed', `|| !previous.get("outputRef").isNull()\n                        && next.get("outputRef").isNull()\n`, `\n`],
  ['J36 exitCode may change', `|| !previous.get("exitCode").isNull()\n                        && !same(previous.get("exitCode"),\n                                next.get("exitCode"))\n`, `\n`],
  ['J37 exitSignal may change', `|| !previous.get("exitSignal").isNull()\n                        && !same(previous.get("exitSignal"),\n                                next.get("exitSignal"))) {`, `) {`],
  ['J38 terminal not frozen', `if (TERMINAL.contains(text(previous.get("run"), "state"))) {\n            return same(previous, next);`, `if (TERMINAL.contains(text(previous.get("run"), "state"))) {\n            return true;`],
  ['J39 rebuild may keep receipt', `|| (rebuilt ? !sameReceipt : sameReceipt);`, `|| (rebuilt ? true : sameReceipt);`],
  ['J40 receipt may change without rebuild', `|| (rebuilt ? !sameReceipt : sameReceipt);`, `|| (rebuilt ? !sameReceipt : true);`],
];
