// One mutant per condition of managed-child-run-record.ts (PR #13265 head).
// Each `find` must occur exactly once in the file.
export const FILE = 'packages/core/src/managed-runtime/managed-child-run-record.ts';
export const MUTANTS = [
  ['T01 kind check dropped', `if (body.kind !== 'shell') {`, `if (false) {`],
  ['T02 start call may be absent', `run.executionCallId === null ||\n    run.effectId !== null ||`, `run.effectId !== null ||`],
  ['T03 effectId allowed', `run.effectId !== null ||\n    run.dispatchId`, `run.dispatchId`],
  ['T04 dispatchId allowed', `run.dispatchId !== null ||\n    run.deliveryId`, `run.deliveryId`],
  ['T05 delivery allowed', `run.delivery !== null ||\n    run.definition`, `run.definition`],
  ['T06 definition allowed', `run.delivery !== null ||\n    run.definition !== null\n  ) {`, `run.delivery !== null\n  ) {`],
  ['T07 receipt before start allowed', `startReceiptRef !== null &&\n    UNSTARTED_EXECUTION_STATES.includes(execution)`, `false &&\n    UNSTARTED_EXECUTION_STATES.includes(execution)`],
  ['T08 attached without receipt', `(execution === 'running_attached' || execution === 'settled')`, `execution === 'settled'`],
  ['T09 settled execution without receipt', `(execution === 'running_attached' || execution === 'settled')`, `execution === 'running_attached'`],
  ['T10 receipt without runtime', `if (startReceiptRef !== null && run.runtime === null) {`, `if (false) {`],
  ['T11 output kind unchecked', `output.kind !== MANAGED_TOOL_RESULT_KINDS.manifest ||\n      output.schemaVersion !== 1`, `output.schemaVersion !== 1`],
  ['T12 output version unchecked', `output.kind !== MANAGED_TOOL_RESULT_KINDS.manifest ||\n      output.schemaVersion !== 1`, `output.kind !== MANAGED_TOOL_RESULT_KINDS.manifest`],
  ['T13 output without receipt', `if (outputRef !== null && startReceiptRef === null) {`, `if (false) {`],
  ['T14 stop reason not closed', `typeof reason !== 'string' ||\n      !Object.values(CHILD_RUN_STOP_REASONS)`, `typeof reason !== 'string' ||\n      !Object.values(CHILD_RUN_STOP_REASONS).length ||\n      !Object.values({})`],
  ['T15 exitCode 256 allowed', `code > 255`, `code > 256`],
  ['T16 negative exitCode allowed', `code < 0 ||`, `code < -1 ||`],
  ['T17 fractional exitCode allowed', `!Number.isInteger(code) ||`, ``],
  ['T18 16-char signal limit +1', `/^[A-Z][A-Z0-9]{0,15}$/`, `/^[A-Z][A-Z0-9]{0,16}$/`],
  ['T19 lowercase signal allowed', `/^[A-Z][A-Z0-9]{0,15}$/`, `/^[A-Za-z][A-Za-z0-9]{0,15}$/`],
  ['T20 stopReason iff terminal dropped', `if ((stopReason === null) !== !TERMINAL_RUN_STATES.includes(run.state)) {`, `if (false) {`],
  ['T21 stopReason fits state dropped', `if (!fitting.includes(stopReason)) {`, `if (false) {`],
  ['T22 settled without settled execution', `(execution !== 'settled' || startReceiptRef === null)`, `startReceiptRef === null`],
  ['T23 settled without receipt', `(execution !== 'settled' || startReceiptRef === null)`, `execution !== 'settled'`],
  ['T24 start_failed with receipt', `(startReceiptRef !== null || execution === null)`, `execution === null`],
  ['T25 start_failed never attempted', `(startReceiptRef !== null || execution === null)`, `startReceiptRef !== null`],
  ['T26 process_failed without receipt', `if (stopReason === 'process_failed' && startReceiptRef === null) {`, `if (false) {`],
  ['T27 quota iff quota reason dropped', `if ((stopReason === 'quota_exceeded') !== quota) {`, `if (false) {`],
  ['T28 evidence on non-exit allowed', `      : exitCode !== null || exitSignal !== null`, `      : false`],
  ['T29 exit without evidence allowed', `      ? exitCode === null && exitSignal === null`, `      ? false`],
  ['T30 start may carry output', `return isExtensionRunStart(record.run) && record.outputRef === null;`, `return isExtensionRunStart(record.run);`],
  ['T31 commandRef may change', `const FIXED_KEYS = ['commandRef', 'kind', 'ownerScopeId', 'shellId'] as const;`, `const FIXED_KEYS = ['kind', 'ownerScopeId', 'shellId'] as const;`],
  ['T32 ownerScopeId may change', `const FIXED_KEYS = ['commandRef', 'kind', 'ownerScopeId', 'shellId'] as const;`, `const FIXED_KEYS = ['commandRef', 'kind', 'shellId'] as const;`],
  ['T33 shellId may change', `const FIXED_KEYS = ['commandRef', 'kind', 'ownerScopeId', 'shellId'] as const;`, `const FIXED_KEYS = ['commandRef', 'kind', 'ownerScopeId'] as const;`],
  ['T34 run successor unchecked', `!isExtensionRunSuccessor(before.run, after.run) ||`, ``],
  ['T35 output may be removed', `(before.outputRef !== null && after.outputRef === null) ||`, ``],
  ['T36 exitCode may change', `!setOnce(before.exitCode, after.exitCode) ||`, ``],
  ['T37 exitSignal may change', `!setOnce(before.exitSignal, after.exitSignal)\n    ) {`, `false\n    ) {`],
  ['T38 terminal not frozen', `return same(before, after);\n    }`, `return true;\n    }`],
  ['T39 rebuild may keep receipt', `before.startReceiptRef === null ||\n          !same(before.startReceiptRef, after.startReceiptRef)`, `true`],
  ['T40 receipt may change without rebuild', `: setOnce(before.startReceiptRef, after.startReceiptRef);`, `: true;`],
  ['T41 receipt may be dropped on rebuild', `before.startReceiptRef === null ||\n          !same(before.startReceiptRef, after.startReceiptRef)`, `before.startReceiptRef === null ||\n          (after.startReceiptRef !== null && !same(before.startReceiptRef, after.startReceiptRef)) || after.startReceiptRef === null`],
];
