// S3 — workspace actions menu on TARGET (default beta-lib): idle 25 s → open
// menu 62 s → close → 65 s closed + focus. Facet/Git reads per phase.
import { launch, openUi, count, isFacet, save, sleep } from './ui.mjs';
const arm = process.argv[2];
const TARGET = process.env.TARGET || 'beta-lib';
const WSKEY = { 'alpha-app': 'alpha', 'beta-lib': 'beta', 'gamma-docs': 'gamma' }[TARGET];
const { browser, page, reqs, t0 } = await launch();
await openUi(page);
const now = () => Date.now() - t0;
const header = page.getByRole('complementary').getByRole('button', { name: new RegExp(`^${TARGET}`) }).first();
await header.waitFor();
await sleep(25_000);
const mine = (r) => r.ws === WSKEY;
const gitW = (r) => mine(r) && (r.kind === 'git' || r.kind === 'git?wait');
const facetW = (r) => mine(r) && (isFacet(r) || r.kind === 'skills');
const phase = {};
const tStart = now();
phase.idle = { facets: count(reqs, facetW, 0, tStart), git: count(reqs, gitW, 0, tStart) };
await header.hover();
const trigger = header.locator('..').getByRole('button', { name: 'Workspace actions' });
await trigger.click();
const menu = page.getByRole('menu');
await menu.waitFor({ timeout: 5000 });
const items0 = (await menu.getByRole('menuitem').allInnerTexts()).map((s) => s.replace(/\s+/g, ' '));
await sleep(1_500);
const items = (await menu.getByRole('menuitem').allInnerTexts()).map((s) => s.replace(/\s+/g, ' '));
const detailsVisibleWithMenu = await page.getByRole('dialog', { name: TARGET }).isVisible();
const mb = await menu.boundingBox();
await page.screenshot({ path: `/root/git/h11644/shots/s3-${arm}-${WSKEY}-menu.png`, clip: { x: 0, y: 0, width: Math.min(1440, Math.round((mb?.x ?? 0) + (mb?.width ?? 400) + 30)), height: Math.min(900, Math.round((mb?.y ?? 0) + (mb?.height ?? 400) + 30)) } });
await sleep(60_500);
const tClose = now();
phase.open = { items0, seconds: Math.round((tClose - tStart) / 1000), detailsVisibleWithMenu, items, facets: count(reqs, facetW, tStart, tClose), git: count(reqs, gitW, tStart, tClose) };
await page.keyboard.press('Escape');
await page.mouse.move(900, 850);
await page.locator('[data-web-shell-composer-editor] .cm-content').click();
await sleep(1_000);
const tClosed = now();
await sleep(65_000);
await page.evaluate(() => window.dispatchEvent(new Event('focus')));
await sleep(1_500);
const tEnd = now();
phase.closed = { menuHidden: !(await menu.isVisible()), seconds: Math.round((tEnd - tClosed) / 1000), facets: count(reqs, facetW, tClosed, tEnd), git: count(reqs, gitW, tClosed, tEnd) };
const timeline = reqs.filter((r) => gitW(r) || facetW(r)).map((r) => `${r.t} ${r.kind}`);
const res = { arm, TARGET, phase, timeline };
save(`s3-${arm}-${WSKEY}`, { ...res, reqs });
console.log(JSON.stringify(res, null, 2));
await browser.close();
