# Hand-written rule-deletion mutants, mirrored TS <-> Java by id suffix.
# Each entry: (id, relative file, old, new[, occurrence (1-based), replace_all])
TS = 'packages/core/src/managed-runtime/managed-channel-record.ts'
AU = 'packages/core/src/managed-runtime/managed-session-authority.ts'
PJ = 'packages/core/src/managed-runtime/managed-extension-projection.ts'
JV = 'packages/sdk-java/managed-agent-server/src/main/java/com/alibaba/qwen/code/managedagent/store/ManagedChannelRecords.java'

M = []
def t(i, desc, old, new, occ=1, f=TS, all_=False): M.append(dict(id='T' + i, lang='ts', file=f, desc=desc, old=old, new=new, occ=occ, all=all_))
def j(i, desc, old, new, occ=1, all_=False): M.append(dict(id='J' + i, lang='java', file=JV, desc=desc, old=old, new=new, occ=occ, all=all_))

# --- scope carriers
t('01', 'user: drop threadId===null', "? senderId !== null && chatId !== null && threadId === null", "? senderId !== null && chatId !== null")
j('01', 'user: drop threadId===null', 'case "user" -> sender != null && chat != null && thread == null;', 'case "user" -> sender != null && chat != null;')
t('02', 'user: drop chatId!==null', "? senderId !== null && chatId !== null && threadId === null", "? senderId !== null && threadId === null")
j('02', 'user: drop chatId!==null', 'case "user" -> sender != null && chat != null && thread == null;', 'case "user" -> sender != null && thread == null;')
t('03', 'thread: xor -> or', "? senderId === null && (chatId === null) !== (threadId === null)", "? senderId === null && (chatId !== null || threadId !== null)")
j('03', 'thread: xor -> or', 'case "thread" -> sender == null && (chat == null) != (thread == null);', 'case "thread" -> sender == null && (chat != null || thread != null);')
t('04', 'thread: drop senderId===null', "? senderId === null && (chatId === null) !== (threadId === null)", "? (chatId === null) !== (threadId === null)")
j('04', 'thread: drop senderId===null', 'case "thread" -> sender == null && (chat == null) != (thread == null);', 'case "thread" -> (chat == null) != (thread == null);')
t('05', 'chat_thread: drop chatId!==null', "? senderId === null && chatId !== null\n", "? senderId === null\n")
j('05', 'chat_thread: drop chatId!==null', 'case "chat_thread" -> sender == null && chat != null;', 'case "chat_thread" -> sender == null;')
t('06', 'chat_thread: drop senderId===null', "? senderId === null && chatId !== null\n", "? chatId !== null\n")
j('06', 'chat_thread: drop senderId===null', 'case "chat_thread" -> sender == null && chat != null;', 'case "chat_thread" -> chat != null;')
t('07', 'single: drop chatId===null', ": senderId === null && chatId === null && threadId === null;", ": senderId === null && threadId === null;")
j('07', 'single: drop chatId===null', 'case "single" -> sender == null && chat == null && thread == null;', 'case "single" -> sender == null && thread == null;')
t('08', 'scope kind enum check removed', "kind !== 'user' &&\n    kind !== 'chat_thread' &&\n    kind !== 'thread' &&\n    kind !== 'single'\n", "false\n")
j('08', 'scope kind enum check removed', 'default -> false;\n        };\n        require(carries', 'default -> sender == null && chat == null && thread == null;\n        };\n        require(carries')
# --- route run pins
t('09', 'route run: allow a delivery line', "    run.runtime !== null ||\n    run.delivery !== null\n  ) {\n    fail('Channel route run", "    run.runtime !== null\n  ) {\n    fail('Channel route run")
j('09', 'route run: allow a delivery line', '                && run.get("runtime").isNull()\n                && run.get("delivery").isNull(),\n', '                && run.get("runtime").isNull(),\n')
t('10', 'route run: effectId not pinned to routeId', "    run.effectId !== routeId ||\n", "")
j('10', 'route run: effectId not pinned to routeId', '                && routeId.equals(run.get("effectId").textValue())\n', '\n')
t('11', 'revisions/generation may be 0', "if (parsed < 1) fail(`${label} must be positive.`);", "")
j('11', 'revisions/generation may be 0', '1,\n                Long.MAX_VALUE', '0,\n                Long.MAX_VALUE', all_=True)
# --- segment plan
t('12', 'segment bound 64 -> 65', "value.length > CHANNEL_DELIVERY_MAX_SEGMENTS)", "value.length > CHANNEL_DELIVERY_MAX_SEGMENTS + 1)")
j('12', 'segment bound 64 -> 65', '&& segments.size() <= MAX_DELIVERY_SEGMENTS,', '&& segments.size() <= MAX_DELIVERY_SEGMENTS + 1,')
t('13', 'empty segment plan allowed', "if (value.length < 1 || ", "if (")
j('13', 'empty segment plan allowed', 'segments.isArray() && !segments.isEmpty()', 'segments.isArray()')
t('14', 'duplicate segmentId allowed', "if (seen.has(segmentId)) {", "if (false) {")
j('14', 'duplicate segmentId allowed', 'require(seen.add(segmentId), ', 'require(seen.add(segmentId) || true, ')
t('15', 'ordinal density dropped', "if (ordinal !== index) {", "if (false) {")
j('15', 'ordinal density dropped', '"ordinal") == index,', '"ordinal") >= 0,')
# --- delivery run pins
t('16', 'delivery run: deliveryId not pinned', "    run.deliveryId !== deliveryId ||\n", "")
j('16', 'delivery run: deliveryId not pinned', '                && deliveryId.equals(run.get("deliveryId").textValue())\n', '\n')
t('17', 'delivery run: target not pinned to channel', "    run.delivery === null ||\n    run.delivery.target !== 'channel'\n", "    run.delivery === null\n")
j('17', 'delivery run: target not pinned to channel', '                && !run.get("delivery").isNull()\n                && "channel".equals(run.get("delivery").get("target")\n                        .textValue()),', '                && !run.get("delivery").isNull(),')
t('18', 'cancelRequested type unchecked', "if (typeof body.cancelRequested !== 'boolean') {", "if (false) {")
j('18', 'cancelRequested type unchecked', 'require(record.get("cancelRequested").isBoolean(),', 'require(true,')
# --- delivery line pins
t('19', 'planned: receipts allowed', "planned: run.state === 'admitted' && settled === 0,", "planned: run.state === 'admitted',")
j('19', 'planned: receipts allowed', 'case "planned" -> "admitted".equals(state) && settled == 0;', 'case "planned" -> "admitted".equals(state);')
t('20', 'sending: all-receipted allowed', "        run.state === 'recovery_blocked') &&\n      settled < segments.length,\n    partial:", "        run.state === 'recovery_blocked'),\n    partial:")
j('20', 'sending: all-receipted allowed', 'case "sending" -> inFlight && settled < segments.size();', 'case "sending" -> inFlight;')
t('21', 'sending: admitted run allowed', "    sending:\n      (run.state === 'running' ||", "    sending:\n      (run.state === 'admitted' || run.state === 'running' ||")
j('21', 'sending: admitted run allowed', 'case "sending" -> inFlight && settled < segments.size();', 'case "sending" -> (inFlight || "admitted".equals(state)) && settled < segments.size();')
t('22', 'partial: zero receipts allowed', "      settled > 0 &&\n", "")
j('22', 'partial: zero receipts allowed', 'case "partial" -> inFlight && settled > 0\n', 'case "partial" -> inFlight\n')
t('23', 'partial: all receipts allowed', "      settled > 0 &&\n      settled < segments.length,\n", "      settled > 0,\n")
j('23', 'partial: all receipts allowed', 'case "partial" -> inFlight && settled > 0\n                    && settled < segments.size();', 'case "partial" -> inFlight && settled > 0;')
t('24', 'delivered: missing receipts allowed', "delivered: run.state === 'settled' && settled === segments.length,", "delivered: run.state === 'settled',")
j('24', 'delivered: missing receipts allowed', 'case "delivered" -> "settled".equals(state)\n                    && settled == segments.size();', 'case "delivered" -> "settled".equals(state);')
t('25', 'unknown: run reason allowed', "      run.reason === null &&\n", "")
j('25', 'unknown: run reason allowed', 'case "unknown" -> "waiting".equals(state) && reason == null\n', 'case "unknown" -> "waiting".equals(state)\n')
t('26', 'unknown: all receipts allowed', "      run.reason === null &&\n      settled < segments.length,\n", "      run.reason === null,\n")
j('26', 'unknown: all receipts allowed', 'case "unknown" -> "waiting".equals(state) && reason == null\n                    && settled < segments.size();', 'case "unknown" -> "waiting".equals(state) && reason == null;')
t('27', 'rejected: all receipts allowed', "rejected: run.state === 'failed' && settled < segments.length,", "rejected: run.state === 'failed',")
j('27', 'rejected: all receipts allowed', 'case "rejected" -> "failed".equals(state)\n                    && settled < segments.size();', 'case "rejected" -> "failed".equals(state);')
t('28', 'cancelled: request flag not required', "run.state === 'cancelled' && settled === 0 && body.cancelRequested,", "run.state === 'cancelled' && settled === 0,")
j('28', 'cancelled: request flag not required', '"cancelled".equals(state) && settled == 0\n                    && record.get("cancelRequested").booleanValue();', '"cancelled".equals(state) && settled == 0;')
t('29', 'cancelled: receipts allowed', "run.state === 'cancelled' && settled === 0 && body.cancelRequested,", "run.state === 'cancelled' && body.cancelRequested,")
j('29', 'cancelled: receipts allowed', '"cancelled".equals(state) && settled == 0\n                    && record.get("cancelRequested").booleanValue();', '"cancelled".equals(state)\n                    && record.get("cancelRequested").booleanValue();')
# --- starts
t('30', 'delivery start: cancel request allowed', "      !record.cancelRequested &&\n", "")
j('30', 'delivery start: cancel request allowed', '            if (record.get("cancelRequested").booleanValue()) {\n                return false;\n            }\n', '')
t('31', 'delivery start: receipts allowed', "      record.segments.every((segment) => segment.receipt === null)\n", "      true\n")
j('31', 'delivery start: receipts allowed', '                if (!segment.get("receipt").isNull()) {\n                    return false;\n                }\n', '')
# --- route successor
t('32', 'route succ: scope may drift', "      !same(before.scope, after.scope) ||\n", "")
j('32', 'route succ: scope may drift', '                    || !ManagedExtensionRecords.same(previous.get("scope"),\n                            next.get("scope"))\n', '')
t('33', 'route succ: accountId may drift', "      !same(before.accountId, after.accountId) ||\n", "")
j('33', 'route succ: accountId may drift', '                    || !ManagedExtensionRecords.same(previous.get("accountId"),\n                            next.get("accountId"))\n', '')
t('34', 'route succ: instance may drift', "      !same(before.channelInstanceId, after.channelInstanceId) ||\n", "")
j('34', 'route succ: instance may drift', '                    || !ManagedExtensionRecords.same(previous.get("channelInstanceId"),\n                            next.get("channelInstanceId"))\n', '')
t('35', 'route succ: terminal freeze removed', "if (TERMINAL_RUN_STATES.includes(before.run.state)) {\n      return same(before, after);\n    }\n    if (before.routeRevision", "if (before.routeRevision")
j('35', 'route succ: terminal freeze removed', '            if (ManagedExtensionRecords.TERMINAL.contains(\n                    previous.get("run").get("state").textValue())) {\n                return ManagedExtensionRecords.same(previous, next);\n            }\n            long before', '            long before')
t('36', 'route succ: same-revision rebind allowed', "return REBIND_KEYS.every((key) => same(before[key], after[key]));", "return true;")
j('36', 'route succ: same-revision rebind allowed', '                for (String key : REBIND_KEYS) {\n                    if (!ManagedExtensionRecords.same(previous.get(key),\n                            next.get(key))) {\n                        return false;\n                    }\n                }\n', '')
t('37', 'route succ: revision may skip', "after.routeRevision === before.routeRevision + 1 &&", "after.routeRevision > before.routeRevision &&")
j('37', 'route succ: revision may skip', 'return after == before + 1', 'return after > before')
t('38', 'route succ: generation may go backwards', "      after.routeRevision === before.routeRevision + 1 &&\n      after.accountGeneration >= before.accountGeneration\n", "      after.routeRevision === before.routeRevision + 1\n")
j('38', 'route succ: generation may go backwards', '            return after == before + 1\n                    && next.get("accountGeneration").longValue() >= previous\n                            .get("accountGeneration").longValue();', '            return after == before + 1;')
t('51', 'route succ: routeId may drift', "      !same(before.routeId, after.routeId) ||\n", "")
j('51', 'route succ: routeId may drift', '            if (!ManagedExtensionRecords.same(previous.get("routeId"),\n                    next.get("routeId"))\n                    || !ManagedExtensionRecords.same(previous.get("channelInstanceId"),', '            if (!ManagedExtensionRecords.same(previous.get("channelInstanceId"),')
# --- delivery successor
t('39', 'delivery succ: routeRevision may drift', "      before.routeRevision !== after.routeRevision ||\n", "")
j('39', 'delivery succ: routeRevision may drift', '                    || !ManagedExtensionRecords.same(previous.get("routeRevision"),\n                            next.get("routeRevision"))\n', '')
t('40', 'delivery succ: sourceTurnId may drift', "      before.sourceTurnId !== after.sourceTurnId ||\n", "")
j('40', 'delivery succ: sourceTurnId may drift', '                    || !ManagedExtensionRecords.same(previous.get("sourceTurnId"),\n                            next.get("sourceTurnId"))\n', '')
t('41', 'delivery succ: contentRef may drift', "      !same(before.contentRef, after.contentRef) ||\n      before.segments.length", "      before.segments.length")
j('41', 'delivery succ: contentRef may drift', '                    || !ManagedExtensionRecords.same(previous.get("contentRef"),\n                            next.get("contentRef"))) {', '                    ) {')
t('42', 'delivery succ: segment count may change', "      before.segments.length !== after.segments.length ||\n", "")
j('42', 'delivery succ: segment count may change', '            if (beforeSegments.size() != afterSegments.size()) {\n                return false;\n            }\n', '')
t('43', 'delivery succ: segmentId may drift', "          segment.segmentId === other.segmentId &&\n", "")
j('43', 'delivery succ: segmentId may drift', 'if (!ManagedExtensionRecords.same(before.get("segmentId"),\n                        after.get("segmentId"))\n                        || ', 'if (')
t('44', 'delivery succ: segment contentRef may drift', "          same(segment.contentRef, other.contentRef) &&\n", "")
j('44', 'delivery succ: segment contentRef may drift', '                        || !ManagedExtensionRecords.same(before.get("contentRef"),\n                                after.get("contentRef"))\n', '')
t('45', 'delivery succ: receipt set-once removed', "(segment.receipt === null || same(segment.receipt, other.receipt))", "true")
j('45', 'delivery succ: receipt set-once removed', '                        || (!before.get("receipt").isNull()\n                                && !ManagedExtensionRecords.same(\n                                        before.get("receipt"),\n                                        after.get("receipt")))) {', ') {')
t('46', 'delivery succ: cancel request revocable', "      (before.cancelRequested && !after.cancelRequested) ||\n", "")
j('46', 'delivery succ: cancel request revocable', '            if (previous.get("cancelRequested").booleanValue()\n                    && !next.get("cancelRequested").booleanValue()) {\n                return false;\n            }\n', '')
t('47', 'delivery succ: terminal freeze removed', "if (TERMINAL_RUN_STATES.includes(before.run.state)) {\n      return same(before, after);\n    }\n    return true;", "return true;")
j('47', 'delivery succ: terminal freeze removed', '            if (ManagedExtensionRecords.TERMINAL.contains(\n                    previous.get("run").get("state").textValue())) {\n                return ManagedExtensionRecords.same(previous, next);\n            }\n            return true;', '            return true;')
t('48', 'delivery succ: run-line step unchecked', "      (before.cancelRequested && !after.cancelRequested) ||\n      !isExtensionRunSuccessor(before.run, after.run)\n", "      (before.cancelRequested && !after.cancelRequested)\n")
j('48', 'delivery succ: run-line step unchecked', '            if (!ManagedExtensionRecords.isRunSuccessor(previous.get("run"),\n                    next.get("run"))) {\n                return false;\n            }\n', '')
t('49', 'delivery succ: ordinal compare removed', "          segment.ordinal === other.ordinal &&\n", "")
j('49', 'delivery succ: ordinal compare removed', '                        || !ManagedExtensionRecords.same(before.get("ordinal"),\n                                after.get("ordinal"))\n', '')
t('50', 'delivery succ: deliveryId may drift', "      before.deliveryId !== after.deliveryId ||\n", "")
j('50', 'delivery succ: deliveryId may drift', '            if (!ManagedExtensionRecords.same(previous.get("deliveryId"),\n                    next.get("deliveryId"))\n                    || ', '            if (')
t('52', 'delivery succ: routeId may drift', "      before.routeId !== after.routeId ||\n", "")
j('52', 'delivery succ: routeId may drift', '                    || !ManagedExtensionRecords.same(previous.get("routeId"),\n                            next.get("routeId"))\n                    || !ManagedExtensionRecords.same(previous.get("routeRevision"),', '                    || !ManagedExtensionRecords.same(previous.get("routeRevision"),')
# --- nested field validation
t('53', 'receipt acceptedAt unchecked', "acceptedAt: assertManagedSessionTime(body.acceptedAt, 'receipt.acceptedAt'),", "acceptedAt: body.acceptedAt as number,")
j('53', 'receipt acceptedAt unchecked', '                ManagedExtensionRecords.count(receipt.get("acceptedAt"), 0,\n                        ManagedExtensionRecords.MAX_TIME,\n                        "receipt.acceptedAt");\n', '')
t('54', 'receipt proofRef unchecked', "proofRef: body.proofRef === null ? null : ref(body.proofRef, 'proofRef'),", "proofRef: body.proofRef as never,")
j('54', 'receipt proofRef unchecked', '                if (!receipt.get("proofRef").isNull()) {\n                    ManagedExtensionRecords.durableRef(\n                            receipt.get("proofRef"), "receipt.proofRef");\n                }\n', '')
t('55', 'segment contentRef unchecked', "contentRef: ref(body.contentRef, `segments[${index}].contentRef`),", "contentRef: body.contentRef as never,")
j('55', 'segment contentRef unchecked', '            ManagedExtensionRecords.durableRef(segment.get("contentRef"),\n                    "contentRef");\n', '')
t('56', 'route policyRef unchecked', "policyRef: ref(body.policyRef, 'policyRef'),", "policyRef: body.policyRef as never,")
j('56', 'route policyRef unchecked', '        ManagedExtensionRecords.durableRef(record.get("policyRef"),\n                "policyRef");\n', '')
t('57', 'route start: run start unchecked', "return accepts(() => isExtensionRunStart(parseChannelRoute(value).run));", "return accepts(() => (parseChannelRoute(value), true));")
j('57', 'route start: run start unchecked', '            requireRoute(record);\n            return ManagedExtensionRecords.isRunStart(record.get("run"));', '            requireRoute(record);\n            return true;')
t('58', 'delivery start: run start unchecked', "      isExtensionRunStart(record.run) &&\n", "")
j('58', 'delivery start: run start unchecked', '            return ManagedExtensionRecords.isRunStart(record.get("run"));', '            return true;', occ=2)
# --- Java-only: revert the shared canonical comparator (the review fix)
j('S0', 'comparator revert: JsonNode.equals instead of same()', 'ManagedExtensionRecords.same(', 'java.util.Objects.equals(', all_=True)
# --- authority resource closure + projection registration (TS)
t('A1', 'authority: route policyRef not closed over', "refs = [parseChannelRoute(record).policyRef];", "refs = [];", f=AU)
t('A2', 'authority: delivery contentRef not closed over', "        delivery.contentRef,\n        ...delivery", "        ...delivery", f=AU)
t('A3', 'authority: segment contentRef not closed over', "          segment.contentRef,\n          segment.receipt?.proofRef ?? null,", "          segment.receipt?.proofRef ?? null,", f=AU)
t('A4', 'authority: receipt proofRef not closed over', "          segment.receipt?.proofRef ?? null,\n", "", f=AU)
t('P1', 'projection: route taskKind non-null', "  channel_route: Object.freeze({\n    taskKind: null,", "  channel_route: Object.freeze({\n    taskKind: 'background_shell',", f=PJ)
t('P2', 'projection: delivery keyed by routeId', "return { record, recordId: record.deliveryId, run: record.run };", "return { record, recordId: record.routeId, run: record.run };", f=PJ)
t('P3', 'projection: route keyed by sessionId', "return { record, recordId: record.routeId, run: record.run };", "return { record, recordId: record.sessionId, run: record.run };", f=PJ)


def apply(src, m):
    old, new = m['old'], m['new']
    n = src.count(old)
    if m['all']:
        if n < 1: raise SystemExit(f"{m['id']}: pattern not found")
        return src.replace(old, new)
    if n < m['occ']: raise SystemExit(f"{m['id']}: occurrence {m['occ']} not found (count={n})")
    if m['occ'] == 1 and n != 1: raise SystemExit(f"{m['id']}: pattern not unique (count={n})")
    idx = -1
    for _ in range(m['occ']): idx = src.index(old, idx + 1)
    return src[:idx] + new + src[idx + len(old):]


if __name__ == '__main__':
    import sys, json
    root = sys.argv[1]
    for m in M:
        src = open(f"{root}/{m['file']}").read()
        out = apply(src, m)
        assert out != src, m['id']
    print(json.dumps({'ts': sum(m['lang'] == 'ts' for m in M), 'java': sum(m['lang'] == 'java' for m in M)}))
