// PR #13260 S4 (phase 2): after the crash and reboot: what survived, then retry promote, restart and use the Workspace.
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import * as L from './lib.mjs';
import * as P from './pop.mjs';
import * as M from './w1c.mjs';
const TAG = process.env.TAG ?? 's4';
L.openLog(`s4-post-${TAG}`);
const { say } = L;
const st = JSON.parse(fs.readFileSync(`${L.OUT}/s4-state.json`, 'utf8'));
const DST = st.req.targetRoot; const SRC = st.req.sourceRoot;
const R = { tag: TAG };
const boot = fs.readFileSync('/proc/sys/kernel/random/boot_id', 'utf8').trim();
say(L.hostFacts());
R.rebooted = boot !== st.bootId; R.devsSame = M.stat('/srv/w1c-src') === st.devs.src && M.stat('/srv/w1c-dst') === st.devs.dst;
const tm = M.markerOf(DST);
R.afterCrash = { targetMarker: tm === st.targetMarkerBefore ? 'old (source marker)' : (tm.startsWith('<') ? tm : 'new (target marker)'), tmpFiles: fs.readdirSync(DST).filter((f) => f.includes('.tmp')), row: M.migRow(st.req.migrationOperationId), mount: L.mstr(L.mountRow('a')), fence: M.fenceRow('a') };
say(`   rebooted=${R.rebooted} (boot ${st.bootId.slice(0, 8)} -> ${boot.slice(0, 8)}) loop devs unchanged=${R.devsSame}`);
say(`   after crash: target marker=${R.afterCrash.targetMarker} tmp=[${R.afterCrash.tmpFiles}] ${M.migStr(R.afterCrash.row)} | ${R.afterCrash.mount} | fence=${R.afterCrash.fence?.slice(0, 8)}`);
const q = await M.mig('promote', st.file, { label: `${TAG}-promote-retry` });
const q2 = await M.mig('promote', st.file, { label: `${TAG}-promote-replay`, quiet: true });
R.retry = { exit: q.code, out: M.migSummary(q), replayIdentical: q.stdout === q2.stdout, mount: L.mstr(L.mountRow('a')), root: L.mountRow('a').root, fence: M.fenceRow('a') ?? 'cleared', targetMarker: M.markerBrief(DST), sourceMarkerUnchanged: M.markerOf(SRC) === st.sourceMarker };
say(`   retry: ${R.retry.out} | ${R.retry.mount} root=${R.retry.root} | fence ${R.retry.fence} | replay identical=${R.retry.replayIdentical} | source marker unchanged=${R.retry.sourceMarkerUnchanged}`);
say('  ', L.svc(`ROOT_a=${DST}`, 'start').split('\n').at(-1).slice(0, 220));
const rig = await L.startRig(`s4-${TAG}-after`);
const F1 = new L.HSession(rig.h, st.session, 'ws-a1');
const ld = await F1.load(L.FILES);
const t = await F1.prompt('WRITE notes.txt v3');
const read = (f) => { try { return fs.readFileSync(`${DST}/project/${f}`, 'utf8').trim(); } catch (e) { return `<${e.code}>`; } };
const after = read('notes.txt');
const rw = await rig.h.json(`/session/${st.session}/files/rewind`, { promptId: st.prompts.p2, requestId: randomUUID() }, { clientId: F1.clientId });
R.after = { load: ld.status, turn: P.term(t), notesAfterWrite: after, undoPreCrashPrompt: `${rw.status} ${JSON.stringify(rw.json?.filesChanged)}`, notesAfterUndo: read('notes.txt') };
say(`   after restart: load=${ld.status} turn=${R.after.turn} notes.txt=${after}; undo p2 (pre-migration): ${R.after.undoPreCrashPrompt} -> notes.txt=${R.after.notesAfterUndo}`);
await F1.detach().catch(() => {}); await rig.stop(); L.svc('stop');
fs.writeFileSync(`${L.OUT}/s4-${TAG}.json`, JSON.stringify(R, null, 1));
say('S4-DONE');
