// Each mutant: exact find/replace in the mutation copy; count must be 1.
const P = 'src/main/java/com/alibaba/qwen/code/runtimebroker/';
export default [
  { id: 'M00', what: 'remove the takeover scan hook (behavioural base)', file: P + 'RuntimeBrokerService.java',
    find: 'return scanExecutions(context, stored, null);', rep: 'return CompletableFuture.completedFuture(context);' },
  { id: 'M01', what: 'stop after the first page', file: P + 'RuntimeBrokerService.java',
    find: 'batch.size() < 100\n', rep: 'true\n' },
  { id: 'M02', what: 'next page cursor = first row of the page', file: P + 'RuntimeBrokerService.java',
    find: 'batch.get(batch.size() - 1).getExecutionCallId()', rep: 'batch.get(0).getExecutionCallId()' },
  { id: 'M03', what: 'JDBC cursor inclusive (> becomes >=)', file: P + 'JdbcToolExecutionRepository.java',
    find: 'AND execution_call_id_hash > ? ', rep: 'AND execution_call_id_hash >= ? ' },
  { id: 'M04', what: 'JDBC page without ORDER BY', file: P + 'JdbcToolExecutionRepository.java',
    find: '+ "ORDER BY execution_call_id_hash LIMIT ?";', rep: '+ "LIMIT ?";' },
  { id: 'M05', what: 'in-memory page keeps the largest keys', file: P + 'InMemoryToolExecutionRepository.java',
    find: 'batch.pollLastEntry();', rep: 'batch.pollFirstEntry();' },
  { id: 'M06', what: 'in-memory scan ignores Session ownership', file: P + 'InMemoryToolExecutionRepository.java',
    find: 'if (record.belongsTo(session) && record.needsReconciliation()) {', rep: 'if (record.needsReconciliation()) {' },
  { id: 'M07', what: 'belongsTo ignores the Runtime generation', file: P + 'ToolExecutionRecord.java',
    find: '&& runtimeGeneration == session.getRuntimeGeneration()\n', rep: '\n' },
  { id: 'M08', what: 'JDBC settlement ignores record version', file: P + 'JdbcToolExecutionRepository.java',
    find: '                    || current.getVersion() != expected.getVersion()\n                    || !current.needsReconciliation()', rep: '                    || !current.needsReconciliation()' },
  { id: 'M09', what: 'resolveUnknown no longer UNKNOWN-only (JDBC)', file: P + 'JdbcToolExecutionRepository.java',
    find: 'return resolve(expected, resolutionResult, resolutionTime, true);', rep: 'return resolve(expected, resolutionResult, resolutionTime, false);' },
  { id: 'M10', what: 'takeover settles through resolveUnknown', file: P + 'RuntimeBrokerService.java',
    find: '? executionRepository.resolveUnsettled(current, result, clock.instant())', rep: '? executionRepository.resolveUnknown(current, result, clock.instant())' },
  { id: 'M11', what: 'lookup failure aborts takeover instead of UNRESOLVED', file: P + 'RuntimeBrokerService.java',
    find: 'if (takeover && !(unwrap(error) instanceof Error)) {', rep: 'if (false) {' },
  { id: 'M12', what: 'invalid status aborts takeover instead of UNRESOLVED', file: P + 'RuntimeBrokerService.java',
    find: 'if (takeover && "runtime_execution_status_invalid".equals(failure.getCode())) {', rep: 'if (false) {' },
  { id: 'M13', what: 'no requireOpen after a lookup completes', file: P + 'RuntimeBrokerService.java',
    find: '        lookup.handle((status, error) -> {\n            if (takeover) {\n                requireOpen();\n            }', rep: '        lookup.handle((status, error) -> {' },
  { id: 'M14', what: 'no requireOpen before the settlement write', file: P + 'RuntimeBrokerService.java',
    find: '            if (takeover) {\n                requireOpen();\n            }\n            if (!current.sameIdentity(unknown)) {', rep: '            if (!current.sameIdentity(unknown)) {' },
  { id: 'M15', what: 'no identity check before the settlement write', file: P + 'RuntimeBrokerService.java',
    find: '            if (!current.sameIdentity(unknown)) {\n                throw conflict("runtime_execution_conflict", "Execution identity changed while reconciling");\n            }\n', rep: '' },
  { id: 'M16', what: 'scan steps run synchronously (thenCompose)', file: P + 'RuntimeBrokerService.java',
    find: 'scanned = scanned.thenComposeAsync(ignored -> {', rep: 'scanned = scanned.thenCompose(ignored -> {' },
  { id: 'M17', what: 'no re-read: reconcile the page snapshot', file: P + 'RuntimeBrokerService.java',
    find: 'ToolExecutionRecord current = requireExecution(context, candidate.getExecutionCallId());', rep: 'ToolExecutionRecord current = candidate;' },
  { id: 'M18', what: 'takeover also scans UNKNOWN only (needsReconciliation = UNKNOWN)', file: P + 'ToolExecutionRecord.java',
    find: '        return state == State.EXECUTING || state == State.CANCEL_REQUESTED\n                || state == State.UNKNOWN;', rep: '        return state == State.UNKNOWN;' },
  { id: 'M19', what: 'JDBC scan also returns DISPATCHING', file: P + 'JdbcToolExecutionRepository.java',
    find: "AND execution_state IN ('EXECUTING', 'CANCEL_REQUESTED', 'UNKNOWN') ", rep: "AND execution_state IN ('EXECUTING', 'CANCEL_REQUESTED', 'UNKNOWN', 'DISPATCHING') " },
  { id: 'M20', what: 'no requireOpen at scan step start', file: P + 'RuntimeBrokerService.java',
    find: '            scanned = scanned.thenComposeAsync(ignored -> {\n                requireOpen();\n', rep: '            scanned = scanned.thenComposeAsync(ignored -> {\n' },
];
