S = "packages/sdk-java/managed-agent-server/src/main/java/com/alibaba/qwen/code/managedagent/"
Q = "packages/sdk-java/qwencode/src/main/java/com/alibaba/qwen/code/daemon/"
SRV = "managed-agent-server"
MUTANTS = [
 ("J1", "disabled replica claims answers again (recover() availability guard removed)", S+"service/ActionResponseCoordinator.java",
  "        actions.settleEndedResponses(clock.millis());\n        if (!harness.isAvailable()) {\n            return;\n        }\n", "        actions.settleEndedResponses(clock.millis());\n", SRV),
 ("J2", "ended-answer sweep removed", S+"service/ActionResponseCoordinator.java",
  "        actions.settleEndedResponses(clock.millis());\n", "", SRV),
 ("J3", "approval lease never renewed", S+"service/ActionResponseCoordinator.java",
  "        }, period, period, TimeUnit.MILLISECONDS);", "        }, Long.MAX_VALUE / 4, period, TimeUnit.MILLISECONDS);", SRV),
 ("J4", "lost-lease guard before resolve removed", S+"service/ActionResponseCoordinator.java",
  "            if (leaseLost.get()) {\n                return;\n            }\n", "", SRV),
 ("J5", "cold-cache resolve uses ordinary load again", S+"harness/QwenHostedHarnessConnector.java",
  "session.workspace() != null || workspaceExecution.verifiedRecoveryEnabled(), true);", "workspaceExecution.verifiedRecoveryEnabled(), true);", SRV),
 ("J6", "title-protocol admission check removed", S+"service/ManagedAgentService.java",
  "        if (!harness.supportsFencedTitles()) {", "        if (false && !harness.supportsFencedTitles()) {", SRV),
 ("J7", "Unicode-blank rule reverted to isBlank", S+"service/ManagedAgentService.java",
  "        if (title == null || title.length() > 256\n                || title.codePoints().allMatch(character -> Character.isWhitespace(character)\n                        || Character.isSpaceChar(character) || character == 0xfeff)) {",
  "        if (title == null || title.isBlank() || title.length() > 256) {", SRV),
 ("J8", "superseded 409 flattened to the dependency path", S+"service/ManagedAgentService.java",
  "                        && \"session_mutation_superseded\".equals(refusal.getErrorCode())) {", "                        && \"session_mutation_superseded\".equals(refusal.getErrorCode()) && false) {", SRV),
 ("J9", "completeSessionRename ignores the revision", S+"store/ManagedAgentStore.java",
  "        if (rows.isEmpty() || rows.getFirst().revision() != revision\n", "        if (rows.isEmpty()\n", SRV),
 ("J10", "lifecycle admission ignores an open title delivery", S+"store/ManagedAgentStore.java",
  "        if (hasPendingRenameDelivery(tenantId, sessionId)) {\n            throw new ApiException(HttpStatus.CONFLICT, \"session_operation_active\",",
  "        if (false && hasPendingRenameDelivery(tenantId, sessionId)) {\n            throw new ApiException(HttpStatus.CONFLICT, \"session_operation_active\",", SRV),
 ("J11", "cwd admission ignores an open title delivery", S+"store/ManagedAgentStore.java",
  "                || hasPendingRenameDelivery(tenantId, sessionId)\n", "", SRV),
 ("J12", "migration ignores an open title delivery", S+"store/WorkspaceMigrationStore.java",
  "                + \" AND s.workspace_storage_id = ? AND r.delivery_state <> 'COMPLETED'\") == 0,", "                + \" AND s.workspace_storage_id = ? AND r.delivery_state <> 'COMPLETED'\") >= 0,", SRV),
 ("J13", "abandon ignores the owner/lease", S+"store/ManagedAgentStore.java",
  "                        + \" AND delivery_state = 'RUNNING' AND lease_owner = ? AND lease_until > ?\",\n                Integer.class, tenantId, sessionId, revision, key, owner, clock.millis()) == 1) {",
  "                        + \" AND (? IS NOT NULL OR ? IS NOT NULL)\",\n                Integer.class, tenantId, sessionId, revision, key, owner, clock.millis()) == 1) {", SRV),
 ("J14", "rename recovery worker never completes the receipt", S+"service/SessionRenameCoordinator.java",
  "            store.completeSessionRename(delivery.tenantId(), delivery.idempotencyKey(), delivery.sessionId(),\n                    delivery.title(), attachment.bootId(), delivery.revision());",
  "            if (attachment == null) store.completeSessionRename(delivery.tenantId(), delivery.idempotencyKey(), delivery.sessionId(),\n                    delivery.title(), attachment.bootId(), delivery.revision());", SRV),
 ("J15", "rename recovery runs on a Harness-disabled replica", S+"service/SessionRenameCoordinator.java",
  "        if (!harness.isAvailable()) {\n            return;\n        }\n        for (RenameDelivery", "        for (RenameDelivery", SRV),
 ("J16", "ended-answer sweep drops the decision receipt", S+"store/ManagedActionStore.java",
  "                    matched ? action.decisionReceiptId() : null,\n                    now, now, target.tenantId()", "                    null,\n                    now, now, target.tenantId()", SRV),
 ("J17", "inline rename failure no longer schedules recovery", S+"service/ManagedAgentService.java",
  "                    store.retryRename(delivery, owner, renameClock.millis());\n", "", SRV),
 ("Q1", "SDK skips the revision echo check", Q+"HostedHarnessClient.java",
  "        if (revision != null && !revision.toString().equals(", "        if (false && revision != null && !revision.toString().equals(", "qwencode"),
 ("Q2", "SDK sends a versioned title to an old Harness", Q+"HostedHarnessClient.java",
  "        if (capabilities().getTitleProtocolVersion() != 1) {\n            throw new DaemonProtocolException(\"Hosted Harness title protocol version 1 is required\");",
  "        if (false) {\n            throw new DaemonProtocolException(\"Hosted Harness title protocol version 1 is required\");", "qwencode"),
]
