// b1: live Turn in the browser, then reload: the live card and the restored card must agree.
import fs from 'node:fs';
import * as L from './lib.mjs';
import { chromium, open, SHOTS, transcript, expandShell, openPanel, waitPage, rig } from './pw.mjs';
L.openLog('b1-live');
const n = process.env.WS ?? '23';
const ws = `ws-b1-live-${n}`;
L.register(ws, `st-s${n}`);
const cmd = 'echo "step 1/3 compile"; sleep 3; echo "step 2/3 link"; sleep 3; echo "step 3/3 package"; echo "warning: 2 deprecated flags" >&2; exit 1';
const browser = await chromium.launch();
const t0 = Date.now();
const session = await L.createShellSession(ws, L.shellPrompt('Build the project and report', cmd));
const { page, logs } = await open(browser, session, '&save=opfs');
L.say('session', session);
await page.getByText('Thinking / responding').first().waitFor({ timeout: 20000 }).catch(() => {});
await page.waitForTimeout(2500);
L.say('while running', { ms: Date.now() - t0, transcript: await transcript(page), summaryNodes: await page.locator('[data-managed-tool-result]').count(), outputsButton: await page.getByRole('button', { name: 'Outputs' }).count() });
await page.screenshot({ path: `${SHOTS}/b1-01-running.png` });
await page.getByText('Shell', { exact: true }).first().waitFor({ timeout: 60000 });
L.say('tool card appeared (no reload)', { ms: Date.now() - t0 });
await page.getByText('Completed').first().waitFor({ timeout: 60000 });
await page.waitForTimeout(1500);
await expandShell(page);
const live = await transcript(page);
const liveCard = await page.locator('[data-managed-tool-result]').first().innerText();
L.say('live transcript', live);
await page.screenshot({ path: `${SHOTS}/b1-02-live-card.png` });
await page.reload({ waitUntil: 'load' });
await expandShell(page);
const restored = await transcript(page);
const restoredCard = await page.locator('[data-managed-tool-result]').first().innerText();
L.say('restored transcript', restored);
L.say('live == restored', { transcript: live === restored, card: liveCard === restoredCard, card_text: restoredCard.replace(/\n+/g, ' | ') });
await page.screenshot({ path: `${SHOTS}/b1-03-restored-card.png` });
// outputs panel
await openPanel(page);
let dialog = await waitPage(page);
L.say('panel stdout', (await dialog.innerText()).replace(/\n+/g, ' | '));
await page.screenshot({ path: `${SHOTS}/b1-04-panel-stdout.png` });
await dialog.getByRole('button', { name: /^stderr/ }).click();
await page.waitForTimeout(400);
dialog = await waitPage(page);
L.say('panel stderr', (await dialog.locator('pre[data-managed-output-bytes]').innerText()).replace(/\n+/g, ' | '));
await page.screenshot({ path: `${SHOTS}/b1-05-panel-stderr.png` });
const r = await rig(page);
L.say('content requests', r.requests.map((q) => `${q.status} range=${q.range} if-match=${q.ifMatch ? 'yes' : 'no'} actor=${q.auth}`));
L.say('events', (await L.events(session)).map((e) => `${e.sequence}:${e.type}`).join(' '));
L.say('browser errors', logs);
fs.writeFileSync(`${L.R}/out/b1-live.json`, JSON.stringify({ session, live, restored }, null, 2));
await browser.close();
