import fs from 'node:fs';
const SP = '/private/tmp/claude-501/-Users-wenshao-git-qwen-code-x3/dce4d4a1-a7ec-40d6-ba4b-33ae38c1dbd4/scratchpad';
const css = fs.readFileSync(`${SP}/fig/01-hosted-surrogate-ab.html`, 'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const muts = fs.readFileSync(`${SP}/mut/results.jsonl`, 'utf8').trim().split('\n').map(JSON.parse);
const rows = muts.map((m) => `<tr><td class="mono">${esc(m.name.slice(0, 3))}</td><td>${esc(m.name.slice(4))}</td><td class="${m.verdict === 'KILLED' ? 'good' : 'warn'}">${m.verdict}</td><td class="mono dim">${esc((m.killers[0] ?? (m.verdict === 'SURVIVED' ? 'audit deferred item 2 (no deterministic test)' : '')).replace(/^[A-Za-z]+Test\./, (x) => x))}${m.killers.length > 1 ? ` +${m.killers.length - 1}` : ''}</td></tr>`).join('');
const html = `<!doctype html><meta charset="utf-8"><style>${css}</style><div id="card"><h1>Tests, real faults on MySQL, and mutations</h1><p class="sub">runtime-broker classes of each arm driven against a real Worker and MySQL 8.4.11 (Docker); faults are MySQL triggers on the RECOVERY_BLOCKED write. Machine load 15–45 from unrelated jobs.</p>
<h2>A. Startup deadline (managed-context, real Worker)</h2><table><tr><th>Scenario</th><th>main</th><th>PR</th></tr>
<tr><td class="case">Worker hangs · deadline 4 s · block write fails<br><span class="dim">trigger: SIGNAL SQLSTATE 45000</span></td><td>503 runtime_broker_provision_timeout<br><span class="bad">suppressed=[]</span> (repository failure dropped)</td><td>503 runtime_broker_provision_timeout<br><span class="good">suppressed=[IllegalStateException(SQLException: rig: recovery block write refused)]</span></td></tr>
<tr><td class="case">Worker attests another storage (non-retryable) · deadline 1 s<br>block write stalled 2 s <span class="dim">(trigger: SLEEP)</span> · 6 trials</td><td>5&times; 503 runtime_provision_failed (non-retryable), 1&times; runtime_provision_fenced<br><span class="dim">0/6 answered 409: the handler answers one DB round trip before the deadline</span></td><td><span class="good">6&times; 503 runtime_provision_failed (non-retryable)</span>, binding RECOVERY_BLOCKED<br><span class="dim">the reordering is pinned by the new unit test, which fails on main</span></td></tr></table>
<h2>B. Suites and A/B</h2><table><tr><th>Check</th><th>Result</th></tr>
<tr><td class="case">PR's new/changed tests on merge-base 99adce25</td><td><span class="good">6 fail</span> + 1 new helper test that cannot compile there = the author's "seven"</td></tr>
<tr><td class="case">JdbcRuntimeBrokerMySqlIT twice on one database</td><td>main: 2nd run fails <code>expected: &lt;[1]&gt; but was: &lt;[2]&gt;</code> on MySQL 8.4.11 and MariaDB 10.11.18 · <span class="good">PR: 4/4 runs pass</span></td></tr>
<tr><td class="case">runtime-broker unit + Checkstyle (PR head)</td><td><span class="good">426 run, 0 failures</span>, 2 skipped · 0 violations</td></tr>
<tr><td class="case">managed-agent-server on PR + main 1b69629 (4 commits newer than CI's merge ref)</td><td><span class="good">182 unit · ManagedAgentMySqlIT 14/14 (MariaDB) · Hosted IT 9/9 (MySQL 8.4) · Checkstyle 0</span></td></tr>
<tr><td class="case">Stage F fault gates</td><td>CI (Linux) 39/39 · local 36/39 under load; DurableLocalRuntimeFaultGateTest also fails on main here with the same <code>runtime_provision_fenced</code> (main 1/5 runs, PR 2/6) → load flake, not this PR</td></tr></table>
<h2>C. Mutation sweep — ${muts.filter((m) => m.verdict === 'KILLED').length}/${muts.length} killed (targeted classes, 185 tests each)</h2><table><tr><th>#</th><th>Mutant</th><th>Verdict</th><th>First killing test</th></tr>${rows}</table></div>`;
fs.writeFileSync(`${SP}/fig/extra.json`, JSON.stringify({ '03-tests-faults-mutations': html }));
