import sys; sys.path.insert(0,'.')
from card import render
render('PR #12552 round 3: real worker, previous head vs this head',
 'macOS, JDK 21, Node 24; real `qwen managed-runtime-worker` (dist/cli.js), worker+contract sources identical to head; same harness both arms',
['## scenario                                   8157a218 (R2 head)             9d08c65a (this head)',
 '   N1  C1 worker answers 409 on re-attest    -- live 1,1,2,2,3,3,4,4 LISTEN   ++ live 1,0,1,0,1,0,1,0; 4 ports closed',
 '   N1  D2 SIGSTOP worker, then SIGCONT       -- old pid alive, still LISTEN    ++ old pid gone',
 '   N2  B4 release session on dead worker     -- 503 retryable=true x3          ++ OK true x3',
 '   F3  F1 ready url = LAN ip                 -- Bearer token + scope sent      ++ refused, 0 bytes captured',
 '   new G1 release stale session after        -- 503 retryable=true             ++ OK true; gen2 same id/port,',
 '          recovery, gen2 must stay intact                                           pid alive, workers 1->1',
 '',
 '## unchanged, still green on this head',
 '++ A1 adopt real worker: READY, cold 209 ms; A2 re-attest per warm p50 1.8 ms / p95 3.0 ms',
 '++ A3/A4 SIGTERM, kill -9: first warm 503, next warm new generation; A5 close() ends workers',
 '++ B1 control on dead lease 503 before transport; B4c re-acquire of released id -> 409 conflict',
 '++ D1 hung worker: re-attest times out at 30.0 s, next warm re-provisions; E1 deaf adoption killed',
 '!! E2 adopted worker ignoring SIGTERM alive 6.5 s after close()  (deferred R1-23, expected)',
 '',
 '== harness totals: 9d08c65a 13 pass / 1 fail (E2)   |   8157a218 on B,C,D,F,G: 3 pass / 5 fail',
 '== module suite 87/87, 0 skipped on JDK 21/25/26; checkstyle clean; eslint+prettier clean on the .mjs'],
 'figs/fig1-ab.png')
render('macOS CI red: fencedProvisioningReapsTheWorker is timing-dependent',
 'The fence only fires if the 33 ms renewal tick (operationLease 100 ms / 3) runs before the Node double attests (~60-90 ms here)',
['## CI run 35959440392, macos-latest / Java 21, head 9d08c65a',
 '-- fencedProvisioningReapsTheWorker  0.082 s  FAIL  "Expected ExecutionException ... nothing was thrown"',
 '== same test, previous run 35942592564 (8157a218) macOS: pass; this head ubuntu/windows/MariaDB: pass',
 '',
 '## local, whole LocalProcessRuntimeProvisionerTest class, 4 runs each, only the lease value changed',
 '== lease   first tick   PR test as-is                       with 6-line test fix',
 '.. 100ms   33 ms        P P P P  (0.144-0.150 s)            P P P P',
 '.. 300ms   100 ms       F F F F  (0.088-0.114 s)            P P P P',
 '.. 600ms   200 ms       F F F F  (0.089-0.104 s)            P P P P',
  '.. 60 s    20 s         F F F    (run alone)                P P P P',
 '',
 '!! failing runs take ~0.09 s, the CI failure took 0.082 s: the tick lost the race to the boot',
 '## fix (test only): the fencing double also returns null for the READY compareAndSet',
 '++ deterministic at every lease; still kills a mutant that drops both fenced-exit releases (F F F)',
 '++ suite 87/87 and checkstyle clean with the patch'],
 'figs/fig2-fence-race.png')
render('Mutation: PR tests vs this round\'s fixes (9 mutants)',
 'RuntimeBrokerServiceTest + LocalProcessRuntimeProvisionerTest + HttpRuntimeTransportTest, one mutant at a time, cp backup',
['++ M1 invalidateBinding skips releaseQuietly            KILLED  failedReattestationRetires..., deadLeaseReleases...',
 '++ M2 release on dead lease back to requireUsableLease   KILLED  deadLeaseReleases..., deadLeaseReleaseStaysBusy...',
 '++ M3 local release skips invalidateBinding             KILLED  deadLeaseReleasesTheSessionWithoutCallingTransport',
 '++ M4 local release drops the runtime_session_busy guard KILLED  deadLeaseReleaseStaysBusyWhileAnExecutionIsUnsettled',
 '++ M6 local release keeps the session context           KILLED  deadLeaseReleasesTheSessionWithoutCallingTransport',
 '++ M7 local release skips finishSessionRelease          KILLED  deadLeaseReleasesTheSessionWithoutCallingTransport',
 '++ M8 ready url check: scheme only (host dropped)        KILLED  rejectsANonLoopbackReadyUrlBeforeSendingTheToken',
 '!! M5 local release ignores an in-flight release        survived',
 '!! M9 ready url check: host only (scheme dropped)        survived  (https://127.0.0.1 accepted)',
 '',
 '== 7/9 killed. Both survivors are small; neither blocks.'],
 'figs/fig3-mutation.png')
