M = {
'M01 gate: restore exact-size match (revert superset)': ("    if (backup.size === 0) return false;\n", "    if (backup.size === 0 || destination.size !== backup.size) return false;\n"),
'M02 sort: drop targetGeneration key': ("        right.targetGeneration - left.targetGeneration ||\n        right.orderMs - left.orderMs,", "        right.orderMs - left.orderMs,"),
'M03 sort: drop orderMs tiebreak': ("        right.targetGeneration - left.targetGeneration ||\n        right.orderMs - left.orderMs,", "        right.targetGeneration - left.targetGeneration,"),
'M04 sort: live mtime instead of persisted orderMs': ("      let orderMs = journal.orderMs;\n", "      let orderMs: number | undefined = Math.floor(Number(stats.mtimeMs));\n"),
'M05 no orderMs stamp at creation': ("        orderMs: Date.now(),\n", ""),
'M06 windowRefusal ignores rollbackHeld': ("    return journal.rollbackHeld !== false && process.platform === 'win32'", "    return process.platform === 'win32'"),
'M07 no in-memory sync after marker': ("    journal.rollbackBlocked = rollbackBlocked;\n    journal.cleanupPending = cleanupPending;\n    journal.rollbackRetryAt = rollbackRetryAt;\n    journal.rollbackHeld = rollbackHeld;\n", ""),
'M08 fault gets no window (old rule)': ("      pendingStep === 'rollback' || reason === 'held'", "      reason === 'held'"),
'M09 recovery: older sibling not held back': ("        if (decided !== null) {\n          // A newer journal", "        if (false) {\n          // A newer journal"),
'M10 recovery: rethrow at once (no firstUnrecoverable)': ("          if (firstUnrecoverable === null) firstUnrecoverable = error;\n", "          throw error;\n"),
'M11 classify: skip cleanupPending-on-disk check': ("    if (await this.journalCleanupPendingOnDisk(journalPath)) throw error;\n", ""),
'M12 classify: DirectoryLocked counted as fault': ("    if (error instanceof ExtensionDirectoryLockedError) return 'held';\n", "    if (error instanceof ExtensionDirectoryLockedError) return 'fault';\n"),
'M13 guard: fresh budget per journal': ("        if (!(await this.attemptRollback(journal, journalPath, budget))) {\n          decided = 'held';\n          deferredJournal = journal;", "        if (!(await this.attemptRollback(journal, journalPath, { remainingMs: LOCK_RETRY_BUDGET_MS }))) {\n          decided = 'held';\n          deferredJournal = journal;"),
'M14 guard: older sibling not held back': ("      if (decided !== null) {\n        if (\n          !(await this.recordPendingStep(", "      if (false) {\n        if (\n          !(await this.recordPendingStep("),
'M15 validate: rollbackHeld type unchecked': ("        (journal.rollbackHeld !== undefined &&\n          typeof journal.rollbackHeld !== 'boolean') ||\n", ""),
'M16 validate: orderMs unchecked': ("        (journal.orderMs !== undefined &&\n          (!Number.isSafeInteger(journal.orderMs) ||\n            (journal.orderMs as number) < 0)) ||\n", ""),
'M17 recovery: one group for all destinations': ("      const destination = path.resolve(entry.journal.destinationDirectory);\n", "      const destination = 'all';\n"),
'M18 cleanup mark always held': ("          isDirectoryLockError(error) ? 'held' : 'fault',\n", "          'held',\n"),
'M19 window branch: legacy/fault treated as held': ("          decided = journal.rollbackHeld ? 'held' : 'fault';\n", "          decided = 'held';\n"),
'M20 orderMs stamp not persisted': ("        try {\n          await atomicWriteJSON(journalPath, journal, {\n            mode: 0o600,\n            forceMode: true,\n            noFollow: true,\n          });\n        } catch (error: unknown) {\n          debugLogger.warn(\n            'extension transaction order key not persisted:',", "        try {\n          void atomicWriteJSON;\n        } catch (error: unknown) {\n          debugLogger.warn(\n            'extension transaction order key not persisted:',"),
}
