// Mutant definitions for PR 12946. Each: file (repo-relative), find (exact,
// must occur once), replace, and the test command group to run.
const RT = 'packages/cli/src/serve/managed-mcp-runtime.ts';
const HS = 'packages/cli/src/serve/hosted-mcp-session.ts';
const HH = 'packages/cli/src/serve/hosted-harness-session.ts';
const CAT = 'packages/sdk-java/managed-agent-server/src/main/java/com/alibaba/qwen/code/managedagent/service/ManagedMcpCatalogService.java';
const STORE = 'packages/sdk-java/managed-agent-server/src/main/java/com/alibaba/qwen/code/managedagent/store/ManagedExtensionRecordStore.java';
const PROTO = 'packages/sdk-java/runtime-broker/src/main/java/com/alibaba/qwen/code/runtimebroker/ManagedMcpProtocol.java';
module.exports = [
  { id: 'M1', what: 'discovery invalidation during listing ignored (tools)', file: RT, group: 'ts',
    find: "changes.tools === connection.catalogChanges.tools\n            ? values[0].state\n            : 'stale'", replace: 'values[0].state' },
  { id: 'M2', what: 'Runtime accepts conflicting reuse of an operation id', file: RT, group: 'ts',
    find: '        existing.fingerprint !== content\n', replace: '        false\n' },
  { id: 'M3', what: 'failed discovery replaces the previous list (no stale fallback)', file: RT, group: 'ts',
    find: "result.state === 'failed' && previous", replace: 'false' },
  { id: 'M4', what: 'Harness drops the argument-digest identity check', file: HS, group: 'ts',
    find: '        record.argsRef.digest !== digest(request) ||\n', replace: '' },
  { id: 'M5', what: '60 KiB raw-result limit disabled', file: RT, group: 'ts',
    find: 'Buffer.byteLength(JSON.stringify(result)) > MAX_RESULT_BYTES', replace: 'Buffer.byteLength(JSON.stringify(result)) > MAX_RESULT_BYTES * 1000' },
  { id: 'M6', what: 'stdio server inherits the whole worker environment', file: RT, group: 'ts',
    find: "                ...Object.fromEntries(\n                  DEFAULT_INHERITED_ENV_VARS.map((key) => [key, '']),\n                ),", replace: '                ...process.env,' },
  { id: 'M7', what: 'method-not-found no longer means an empty complete list', file: RT, group: 'ts',
    find: "objectOrUndefined(error)?.['code'] === -32601", replace: "objectOrUndefined(error)?.['code'] === -32602" },
  { id: 'M8', what: 'invoke skips the catalog capability check', file: RT, group: 'ts',
    find: '      if (!permitted)\n', replace: '      if (false && !permitted)\n' },
  { id: 'M9', what: 'unknown() drops the physical hold (pending) early', file: RT, group: 'ts',
    find: "    if (operation.view.state === 'settled') return;\n", replace: "    if (operation.view.state === 'settled') return;\n    operation.connection?.pending.delete(operation.control.operationId);\n" },
  { id: 'M10', what: 'cancel of an undispatched intent goes to the Runtime', file: HS, group: 'ts',
    find: "    if (record.run.execution === 'intent') {\n      await this.commitOperation({\n        ...record,\n        cancelRequested: true,", replace: "    if (false) {\n      await this.commitOperation({\n        ...record,\n        cancelRequested: true," },
  { id: 'M11', what: 'prompt admitted while an MCP operation is pending', file: HH, group: 'ts',
    find: '    if (session.blocked || session.mcp?.hasPendingOperations())\n', replace: '    if (session.blocked)\n' },
  { id: 'M12', what: 'configure grant need not name the configuration', file: RT, group: 'ts',
    find: '        grant.operationId !== control.operationId) ||\n', replace: '        false) ||\n' },
  { id: 'M13', what: 'Harness accepts configurations owned by two Runtime Sessions', file: HS, group: 'ts',
    find: '    if (owners.size > 1) throw new HostedMcpRecoveryRequiredError();\n', replace: '' },
  { id: 'M14', what: '16-connection quota disabled', file: RT, group: 'ts',
    find: '.length >= MAX_CONNECTIONS\n', replace: '.length >= MAX_CONNECTIONS * 100\n' },
  { id: 'M15', what: '32 in-flight quota disabled', file: RT, group: 'ts',
    find: ') >= MAX_INFLIGHT\n', replace: ') >= MAX_INFLIGHT * 100\n' },
  { id: 'M16', what: 'late response after timeout ignored', file: RT, group: 'ts',
    find: '            const pending = connection.pending.get(message.id);\n            if (pending) {', replace: '            const pending = connection.pending.get(message.id);\n            if (pending && pending.view.state === \'running\') {' },
  { id: 'J1', what: 'public catalog shows released servers as live', file: CAT, group: 'server',
    find: 'discovery.put(kind, active && Set.of', replace: 'discovery.put(kind, Set.of' },
  { id: 'J2', what: 'MCP operation need not bind to an active settled configuration', file: STORE, group: 'server',
    find: '                require("active".equals(config.get("releaseState").textValue())', replace: '                require(true || "active".equals(config.get("releaseState").textValue())' },
  { id: 'J3', what: 'one server revision may name two definition digests', file: STORE, group: 'server',
    find: '                require(ManagedExtensionRecords.isDefinitionPinConsistent(', replace: '                require(true || ManagedExtensionRecords.isDefinitionPinConsistent(' },
  { id: 'J4', what: 'MCP records leak into the public task list', file: STORE, group: 'server',
    find: '" session_scope_key = ? AND task_kind IS NOT NULL" + cursor', replace: '" session_scope_key = ?" + cursor' },
  { id: 'J5', what: 'catalog/args/result refs not checked against committed resources', file: STORE, group: 'server',
    find: '                    requireReference(resources.apply(ref.get("resourceId").textValue()), ref);', replace: '                    // mutant: reference check removed' },
  { id: 'J6', what: 'Broker forwards MCP controls for another Session', file: PROTO, group: 'broker',
    find: '!isOperation(operation) || !expected.equals(operation.get("sessionKey"))', replace: '!isOperation(operation)' },
  { id: 'J7', what: 'Broker lets tool_call through the control route', file: PROTO, group: 'broker',
    find: '!Set.of("resource_read", "prompt_get").contains(requestKind)', replace: '!Set.of("resource_read", "prompt_get", "tool_call").contains(requestKind)' },
  { id: 'J8', what: 'Broker accepts a response from another Runtime Session', file: PROTO, group: 'broker',
    find: '                || !session.getRuntimeSessionId().equals(envelope.get("runtimeSessionId"))\n', replace: '' },
];
