S = 'dist/chunks/server-KC74N2DY.js'
J = 'dist/chunks/chunk-JYWURPS4.js'
MUTANTS = [
 ('M1', 'author defect 1: drop lenientToolWarmup (config init fails)', S,
  'skipFileCheckpointing:true,lenientToolWarmup:true});const authType',
  'skipFileCheckpointing:true});const authType'),
 ('M2', 'author defect 2: unfiltered setHistory(history)', S,
  'setHistory(history.filter((entry,index)=>entry.role!=="user"||history[index+1]?.role==="model"))',
  'setHistory(history)'),
 ('M3', 'history dropped entirely: setHistory([])', S,
  'setHistory(history.filter((entry,index)=>entry.role!=="user"||history[index+1]?.role==="model"))',
  'setHistory([])'),
 ('M4', 'local tools stay registered and advertised', S,
  'for(const tool of registry.getAllTools())registry.unregisterTool(tool.name);await client.setTools();if(registry.getFunctionDeclarations().length!==0){',
  'await client.setTools();if(false){'),
 ('M5', 'model tool call silently ignored (turn completes)', S,
  'throw new Error("Hosted Harness no-tool turn refused a tool call.")',
  'void 0'),
 ('M6', 'protocol header not required (426 gate removed)', J,
  'if(req.get(HOSTED_HARNESS_PROTOCOL_HEADER)!==String(HOSTED_HARNESS_PROTOCOL_VERSION)){',
  'if(false){'),
 ('M7', 'stale boot id header accepted', J,
  'if(requestedBootId.toLowerCase()!==contract.bootId){',
  'if(false){'),
 ('M8', 'store writerId not bound to boot id', S,
  'if(store.writerId!==contract.bootId){',
  'if(false){'),
 ('M9', 'duplicate submission not idempotent', S,
  'const existing=session.admissions.get(promptId);',
  'const existing=void 0;'),
 ('M10', 'SSE ignores Last-Event-ID (replays from 0)', S,
  'const after=Number(req.get("Last-Event-ID")??"0");',
  'const after=0;'),
 ('M11', 'cancelled turn reported as failure', S,
  'state=abort.signal.aborted?"cancelled":"error";',
  'state="error";'),
 ('M12', 'cancel endpoint is a no-op', S,
  'session.active?.abort.abort();',
  'void 0;'),
 ('M13', 'detach/close does not seal the Store writer', S,
  'try{await session.managed.close();sessions.delete(req.params["id"]);',
  'try{sessions.delete(req.params["id"]);'),
 ('M14', 'private route allowlist removed (pre-auth gate)', S,
  'app.use((req,res,next)=>{if(req.path==="/health"||req.path==="/capabilities"||req.path==="/session"||req.path.startsWith("/session/"))next();else res.sendStatus(404)})',
  'void 0'),
 ('M15', 'post-session 404 fallthrough removed', S,
  'app.use((req,res,next)=>{if(req.path==="/capabilities"||req.path==="/health")next();else res.sendStatus(404)})}const mutate',
  'void 0}const mutate'),
 ('M16', 'Store outage mapped to 500 instead of 503', S,
  'error2(res,503,"managed_session_open_failed")',
  'error2(res,500,"managed_session_open_failed")'),
 ('M17', 'loopback check dropped from profile validation', J,
  'if(!isLoopbackBind(opts.hostname)){throw new Error("--profile hosted-harness requires a loopback --hostname.")}',
  ''),
 ('M18', 'hosted profile no longer forces requireAuth', S,
  'if(opts.profile==="hosted-harness")opts={...opts,requireAuth:true};',
  ''),
 ('M19', 'unfinished model stream accepted as completed', S,
  'if(!finished)throw new Error("Hosted Harness model turn did not finish.");',
  ''),
]
