const fs = require('fs');
const pad = (s, n) => s.padEnd(n);
const r3 = (p, a, b, c) => `${p} ${pad(a, 40)} ${pad(b, 24)} ${c}`.trimEnd();
const gate = [
  r3('##', 'tree / database', 'job', 'result'),
  r3('++', 'PR cc0e2e3a / MySQL 8.4.7 (native)', 'CI-equivalent full', 'pass - 170 unit, 8 Hosted IT methods (Workspace class 5 incl. FG6e,'),
  r3('  ', '', '', '       Harness 2, FG6c crashes 1), Checkstyle 0, failsafe check OK (168 s)'),
  r3('++', 'PR cc0e2e3a / MariaDB 10.11.18', 'Workspace IT class', 'pass - 5/5 in 53.3 s (normal, FG6a, FG6b, FG6d, FG6e)'),
  r3('++', 'PR (+) #12848 dfabe7c7 / MySQL 8.4.7', 'CI-equivalent full', 'pass - clean merge, 172 unit, 8 Hosted IT, Checkstyle 0'),
  r3('==', 'PR (+) main bd45b95f', 'textual merge', 'clean; main moved only in packages/core and web-shell'),
  r3('==', 'CI job 108942860455 / MySQL 8.4.6', 'hosted-harness-mysql', 'pass - HOSTED_SSE_GAP_OK, class 5/5 in 56.6 s'),
  '',
  '## repeats of the FG6e method alone (PR head, unmodified)',
  '++ MySQL 8.4.7     9/9 pass   4.9 - 5.6 s    public ids [1,2,3]  web ids [1,2,3]  every run',
  '++ MariaDB 10.11   5/5 pass   6.4 - 6.8 s    public ids [1,2,3]  web ids [1,2,3]  every run',
  '== machine load average 17-33 throughout; no leftover Harness/worker/driver processes afterwards',
  '',
  '## independent SQL after a MySQL run (session fe47360f, Turn b5efc2dc)',
  '   managed_agent_event        1  session.created          source_key  NULL',
  '                              2  item.output_text.delta   source_key  <boot>:<epoch>:12',
  '                              3  turn.completed  terminal source_key  <boot>:<epoch>:14',
  '   qwen_tool_execution        1 row   SETTLED / success / dispatch_generation 1',
  '   qwen_runtime_session       RELEASED        workspace execution lease holder  NULL',
  '!! managed_agent_turn         0 rows          managed_agent_session.harness_last_event_id = 0',
];
const r4 = (p, id, a, b, c) => `${p} ${pad(id, 3)} ${pad(a, 58)} ${pad(b, 35)} ${c}`.trimEnd();
const mut = [
  r4('##', '', 'production mutant (applied alone, gate unchanged)', 'FG6e gate', '170 unit tests'),
  '== author\'s mutants, re-run as calibration',
  r4('++', 'A1', 'public stream ignores Last-Event-ID', 'KILLED  resumed [1,2]', 'killed (2)'),
  r4('++', 'A2', 'WebShell stream ignores afterSequence', 'KILLED  resumed [1,2]', 'SURVIVES  <- only FG6e'),
  r4('++', 'A3', 'public replay frame: SSE id 2 sent as 20', 'KILLED  id != payload sequence', 'killed (4)'),
  r4('++', 'A4', 'WebShell replay frame: SSE id 2 sent as 20', 'KILLED  id != payload sequence', 'SURVIVES  <- only FG6e'),
  r4('++', 'A5', 'replay SQL  sequence_id > ?  becomes  >=', 'KILLED  resumed [1,2]', 'killed (6)'),
  '== new mutants: replay -> live hand-off and the live path',
  r4('++', 'N1', 'public stream does not advance its cursor after replay', 'KILLED  dup loop [1,2,2,3,2,3..]', 'killed (4)'),
  r4('++', 'N2', 'WebShell stream does not advance its cursor after replay', 'KILLED  dup loop', 'SURVIVES  <- only FG6e'),
  r4('++', 'N3', 'public live (hub) frame: SSE id = sequence + 13', 'KILLED  id != payload sequence', 'killed (5)'),
  r4('++', 'N4', 'hub publish() never wakes subscribers', 'KILLED  terminal never arrives', 'killed (12)'),
  r4('++', 'N8', 'appendEvent (relay path) drops publishAfterCommit', 'KILLED  terminal never arrives', 'killed (4)'),
  '== guards FG6e cannot reach by construction',
  r4('!!', 'N5', 'hub re-delivers the cursor event (inclusive tail)', 'survives  (held terminal)', 'killed (3)'),
  r4('!!', 'N6', 'recordHarnessEvents drops publishAfterCommit', 'survives  (path not used)', 'killed (1)'),
  r4('!!', 'N7', 'appendEvents (Harness batch) skips a sequence number', 'survives  (path not used)', 'killed (7)'),
  '',
  '## FG6e + unit suite together kill 13/13; FG6e alone kills 10/13 and is the only test that kills',
  '## A2, A4 and N2 - every WebShell-stream mutant tried survives the 170 unit tests',
];
const probes = [
  '## where each event reaches the resumed observers (unmodified code; hub state read by reflection)',
  '   clients aborted, FIFO still blocked      hub refs 2  buffered []    server has not noticed the disconnect',
  '   event 2 committed during the gap         hub refs 0                 old streams end on their first write',
  '   resumed, caught up to 2                  hub refs 2  buffered []    event 2 came from SQL replay',
  '   terminal released                        hub refs 2  buffered [3]   event 3 came live through the hub',
  '',
  '## driver variants (production code unmodified)',
  '++ race: terminal released 0-60 ms into the reconnect     10/10   public [2,3]  web [2,3]',
  '++ late: terminal committed before the reconnect           3/3    public [2,3]  web [2,3]  (both from replay)',
  '++ default intervals: poll 5 s / heartbeat 15 s            2/2    pass',
  '',
  '## is the 60 s poll/heartbeat override load-bearing?',
  '-- N4 (dead hub) with default 5 s poll      SURVIVES  the 5 s SQL reconcile delivers the terminal inside the 10 s wait',
  '++ N4 (dead hub) with the PR\'s 60 s poll    KILLED    Timed out after 10000ms waiting for id 3',
  '!! N5 + race variant                        10/10 survive: random jitter never lands in the ms subscribe/replay window',
  '',
  '## is the shutdownNow() in the IT finally block load-bearing?',
  '++ as in the PR                             FG6e method  6.4 s',
  '-- shutdownNow() skipped                    FG6e method 67.3 s  (parked stream tasks hold ExecutorService.close() ~60 s)',
];
const spec = [
  { name: '01-gate-matrix', title: 'FG6e gate on a real stack - PR head, merged trees, two databases, CI',
    subtitle: 'Packaged CLI built from each tree, real Hosted Harness + Workspace Edit worker, Spring + Broker + JDBC in the IT; deterministic fake model; macOS arm64, Node 22.23.2, Java 21',
    lines: gate,
    note: 'Every run matches CI: both observers see exactly [1,2,3], one x -> xx effect, Broker acquire/prepare/start/release exactly once each, zero cancel. The SQL ledger also shows the relay never creates a public Turn (0 turn rows, harness cursor 0).' },
  { name: '02-mutants', title: 'FG6e mutation sensitivity vs the existing 170 unit tests',
    subtitle: 'One production mutant at a time on MySQL 8.4.7; the gate, driver and probe are unchanged; each kill is a behavioural assertion or the 10 s catch-up wait, never a startup failure',
    lines: mut,
    note: 'N5/N6/N7 are outside what FG6e can see (the held terminal keeps replay and hub from overlapping; the relay writes through appendEvent, not the Harness batch path). The unit suite covers all three, so there is no hole.' },
  { name: '03-probes', title: 'FG6e probes - hub lifecycle, no-barrier race, late resume, default intervals',
    subtitle: 'Probe copy of the driver/IT only (FG6E_PROBE modes + a non-asserting hub dump); every other file identical to the PR head',
    lines: probes,
    note: 'The subscribe-before-replay order in ManagedEventStreamService holds with the barrier removed. The 60 s intervals are what make a dead hub fail the gate, and shutdownNow() is what keeps them from costing a minute per run - both deserve a one-line comment.' },
];
fs.writeFileSync(process.argv[2], JSON.stringify(spec, null, 1));
