// Generator probe: regenerate WebShell types from base/head/mutated specs
// with the PR's own generator and openapi-typescript, then diff.
import { readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

const SP = '/private/tmp/claude-501/-Users-wenshao-git-qwen-code-x3/12fa9b24-1d30-4fad-b831-ba32169a2e71/scratchpad';
const PR = `${SP}/wt-pr`;
const BASE = `${SP}/wt-base`;
const OUT = `${SP}/pr12998/gen`;
const SPEC = 'packages/sdk-java/managed-agent-server/src/main/resources/openapi/managed-agent-public-api.openapi.json';
const GEN = 'packages/web-shell/client/components/managed/generated/managed-agent-api.ts';

const gen = await import(pathToFileURL(`${PR}/packages/web-shell/scripts/generate-managed-agent-api.mjs`));
const { default: openapiTS, astToString } = await import(pathToFileURL(`${PR}/node_modules/openapi-typescript/dist/index.mjs`));
const HEADER = `// Generated by packages/web-shell/scripts/generate-managed-agent-api.mjs.
// Do not edit; run \`npm run generate:managed-agent-api\` in packages/web-shell.
`;
const render = async (spec) => HEADER + astToString(await openapiTS(gen.webShellContract(structuredClone(spec)), { defaultNonNullable: false }));
const load = async (root) => JSON.parse(await readFile(`${root}/${SPEC}`, 'utf8'));
const diffLines = (a, b, name) => {
  execFileSync('mkdir', ['-p', OUT]);
  return writeFile(`${OUT}/${name}.ts`, b).then(async () => {
    await writeFile(`${OUT}/_ref.ts`, a);
    try {
      execFileSync('diff', ['-u', `${OUT}/_ref.ts`, `${OUT}/${name}.ts`]);
      return { changed: 0, diff: '' };
    } catch (e) {
      const d = e.stdout.toString();
      await writeFile(`${OUT}/${name}.diff`, d);
      const changed = d.split('\n').filter((l) => /^[+-][^+-]/.test(l)).length;
      return { changed, diff: d };
    }
  });
};

const head = await load(PR);
const base = await load(BASE);
const committedHead = await readFile(`${PR}/${GEN}`, 'utf8');
const committedBase = await readFile(`${BASE}/${GEN}`, 'utf8');
const genHead = await render(head);
const genBase = await render(base);
const viaScript = await gen.renderManagedAgentApi();

const results = [];
results.push(['G1 head spec -> generator == committed head file', genHead === committedHead && viaScript === committedHead]);
results.push(['G2 base spec -> generator == committed base file', genBase === committedBase]);
const d = await diffLines(genBase, genHead, 'head-vs-base');
results.push([`G3 base->head generated diff: ${d.changed} changed lines`, true]);
console.log(d.diff.split('\n').filter((l) => /^[+-][^+-]/.test(l)).map((l) => l.slice(0, 160)).join('\n'));

// Activation probes: what the generated client would look like if a later
// slice un-plans only part of the task_cancel surface.
const cond = (spec, schema) => spec.components.schemas[schema].allOf.find((e) => e.if?.properties?.type?.const === 'task_cancel' && e.then?.properties?.status);
const unplan = (node) => { delete node['x-qwen-implementation-status']; };

const a1 = structuredClone(head);
unplan(cond(a1, 'WebShellCommandOperation'));
unplan(cond(a1, 'PublicCommandOperation'));
const r1 = await diffLines(genHead, await render(a1), 'A1-unplan-conditional-only');
results.push([`A1 un-plan only the new conditional: ${r1.changed} changed lines`, true]);
console.log('--- A1 diff ---\n' + r1.diff.split('\n').filter((l) => /^[+-][^+-]/.test(l)).map((l) => l.slice(0, 200)).join('\n'));

const a2 = structuredClone(a1);
for (const s of ['WebShellCommandOperation']) {
  const props = a2.components.schemas[s].properties;
  unplan(props.failureCode);
  unplan(props.taskId);
}
const r2 = await diffLines(genHead, await render(a2), 'A2-unplan-conditional-and-fields');
results.push([`A2 un-plan conditional + taskId + failureCode: ${r2.changed} changed lines`, true]);
console.log('--- A2 diff ---\n' + r2.diff.split('\n').filter((l) => /^[+-][^+-]/.test(l)).map((l) => l.slice(0, 200)).join('\n'));

// Leak probe: remove the planned marker from the conditional without the
// fields and check whether the generated-sync test would notice (it compares
// committed vs regenerated, so any change in output is caught at CI time).
for (const [label, ok] of results) console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}`);
await writeFile(`${OUT}/summary.json`, JSON.stringify({ results, g3: d.changed, a1: r1.changed, a2: r2.changed }, null, 2));
