// S12 — a --bg launch from a home with no auth selected (fresh install shape).
import * as L from './lib.mjs';
const C = new L.Checks('s12-no-auth');
const T = new L.Transcript('s12-no-auth');
const UUID = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/;
const sc = L.scenario('head', 's12');
L.writeFileSync(L.path.join(sc.qhome, 'settings.json'), '{}');
const out = L.path.join(sc.cwd, 'noauth.txt');
const led0 = L.ledgerLen();
T.title('no auth type selected in settings (fresh-install shape), OPENAI_* env present (head b8387983)');
T.cmd(`qwen --bg "BGWRITE:${out}"`);
const r = L.qwen(sc, ['--bg', `BGWRITE:${out}`]);
T.out(r.stdout.split('\n')[0]); T.err(r.stderr); T.exit(r.code, r.ms);
const sid = UUID.exec(r.stdout)?.[1];
const wrote = await L.waitFor(() => L.existsSync(out), { timeout: 25_000 });
const turns = L.ledgerSince(led0).filter((l) => l.lastUser.includes(out)).length;
const client = await L.supervisorClient(sc);
const strip = (t) => t.replace(/\x1b\][^\x07]*\x07/g, '').replace(/\x1b\[[0-9;?]*[A-Za-z]/g, '').replace(/\r/g, '');
const screen = sid ? strip((await client.logs(sid).catch(() => ({ output: '' }))).output ?? '') : '';
const tail = screen.split('\n').filter((l) => l.trim()).slice(-16).join('\n');
const st = sid ? L.sessionFiles(sc, sid).state : undefined;
T.note(`after 25 s: file written=${!!wrote}; model requests for the task=${turns}; state ${st?.sessionState}/${st?.processState}`);
T.note('worker screen (logs RPC), last lines:');
T.out(tail);
C.check('launch.exit0', r.code === 0);
C.check('worker-ran-task', !!wrote, `written=${!!wrote} turns=${turns}`);
C.save({ sid, wrote: !!wrote, turns, state: st, screenTail: tail });
L.killScenario(sc);
process.exit(0);
