// Test-plan step 3: the replacement admission is definitively rejected (413)
// after the rewind; retry from the failed message; composer draft independent.
import { open, typeAndSend, waitText, sleep, rows, assistantLines, shot, mkLog, openEditor, composerText, modelLog } from './lib.mjs';
const arm = process.argv[2] ?? 'after';
const log = mkLog(`s3-${arm}`);
const { browser, page, net } = await open(arm);
let armed = false;
await page.route('**/session/*/prompt', async (route) => {
  if (armed && route.request().method() === 'POST') {
    armed = false;
    log('>> injected 413 on', route.request().method(), new URL(route.request().url()).pathname.replace(/[0-9a-f-]{36}/, ':id'));
    await route.fulfill({ status: 413, contentType: 'application/json', body: JSON.stringify({ error: 'Prompt too large (injected by probe)' }) });
  } else await route.continue();
});
await typeAndSend(page, 'ALPHA first question');
await waitText(page, 'Reply to ALPHA');
await sleep(800);
await typeAndSend(page, 'NOVEMBER second question');
await waitText(page, 'Reply to NOVEMBER');
await sleep(1500);
await page.locator('[data-web-shell-composer-editor] .cm-content').click();
await page.keyboard.type('UNRELATED DRAFT');
const nModel0 = modelLog(arm).filter((r) => r.isMain).length;
await openEditor(page);
await page.fill('textarea[aria-label="Edit message"]', 'OSCAR retry me');
armed = true;
const m1 = Date.now();
await page.keyboard.press('Enter');
await page.waitForSelector('button[aria-label="Retry sending message"]', { timeout: 20000 });
await sleep(1500);
log('requests', net.filter((r) => r.t >= m1 && /rewind|prompt$/.test(r.u)).map((r) => `${r.m} ${r.u.replace(/[0-9a-f-]{36}/, ':id')}`));
log('rows after rejected send', await rows(page));
log('editor still open?', await page.locator('textarea[aria-label="Edit message"]').count());
log('composer', JSON.stringify(await composerText(page)));
log('toasts', await page.$$eval('[data-web-shell-toast]', (ts) => ts.map((t) => t.innerText.replace(/\s+/g, ' ').trim())));
log('model main requests since edit:', modelLog(arm).filter((r) => r.isMain).length - nModel0);
await shot(page, `s3-${arm}-0-rejected`);
await page.click('button[aria-label="Retry sending message"]');
await waitText(page, 'Reply to OSCAR');
await sleep(2000);
log('rows after retry', await rows(page));
log('assistant after retry', await assistantLines(page));
log('composer after retry', JSON.stringify(await composerText(page)));
await shot(page, `s3-${arm}-1-after-retry`);
await openEditor(page);
log('editor value opened on the retried message:', JSON.stringify(await page.inputValue('textarea[aria-label="Edit message"]')));
await page.fill('textarea[aria-label="Edit message"]', 'PAPA edit after retry');
await page.keyboard.press('Enter');
await waitText(page, 'Reply to PAPA');
await sleep(2000);
const lr = await rows(page), la = await assistantLines(page);
log('rows after PAPA', lr);
log('assistant after PAPA', la);
await page.reload();
await waitText(page, 'Reply to PAPA', 60000);
await sleep(2500);
log('reload equal?', JSON.stringify(lr) === JSON.stringify(await rows(page)) && JSON.stringify(la) === JSON.stringify(await assistantLines(page)));
log('composer after reload', JSON.stringify(await composerText(page)));
await browser.close();
