// Test-plan step 5 through the UI: notification before the last turn, page
// reloaded (replayed transcript), then edit the last turn in place. IME keys.
import { open, typeAndSend, waitText, sleep, rows, assistantLines, shot, mkLog, openEditor } from './lib.mjs';
const arm = process.argv[2] ?? 'after';
const log = mkLog(`s5c-${arm}`);
const { browser, page, net } = await open(arm);
await page.addInitScript(() => {
  window.__keys = [];
  document.addEventListener('keydown', (e) => { if (['Enter', 'Escape', 'Process'].includes(e.key) || e.keyCode === 229) window.__keys.push({ key: e.key, isComposing: e.isComposing, keyCode: e.keyCode, tag: e.target?.tagName }); }, true);
});
await typeAndSend(page, 'BGJOB start a background job');
await waitText(page, 'NOTIF-REPLY', 30000);
await sleep(6000);
await typeAndSend(page, 'KILO after the notification');
await waitText(page, 'Reply to KILO');
await sleep(2000);
await page.reload();
await waitText(page, 'Reply to KILO', 60000);
await sleep(3000);
log('rows (replayed)', await rows(page));
log('assistant (replayed)', await assistantLines(page));
const cdp = await page.context().newCDPSession(page);
await openEditor(page);
await page.fill('textarea[aria-label="Edit message"]', 'LIMA edited ');
await page.focus('textarea[aria-label="Edit message"]');
await page.keyboard.press('End');
const imeMark = Date.now();
await page.evaluate(() => (window.__keys = []));
// IME: start a composition, then press Enter and Escape while it is active
await cdp.send('Input.imeSetComposition', { text: 'bian', selectionStart: 4, selectionEnd: 4 });
await page.keyboard.press('Enter');
await sleep(300);
await cdp.send('Input.imeSetComposition', { text: 'bianji', selectionStart: 6, selectionEnd: 6 });
await page.keyboard.press('Escape');
await sleep(300);
log('keydowns seen during composition', await page.evaluate(() => window.__keys));
log('editor still open during IME Enter/Escape:', await page.locator('textarea[aria-label="Edit message"]').count());
await cdp.send('Input.insertText', { text: '编辑' });
await sleep(300);
log('editor value after IME commit:', JSON.stringify(await page.inputValue('textarea[aria-label="Edit message"]')));
log('requests during IME:', net.filter((r) => r.t >= imeMark && /rewind|prompt$/.test(r.u)).map((r) => r.m + ' ' + r.u));
await shot(page, `s5c-${arm}-0-ime-editor`);
await page.evaluate(() => (window.__keys = []));
await page.keyboard.press('Enter');
await waitText(page, 'Reply to LIMA');
await sleep(2000);
log('plain Enter keydown', await page.evaluate(() => window.__keys));
const liveRows = await rows(page); const liveAsst = await assistantLines(page);
log('LIVE rows after edit', liveRows);
log('LIVE assistant after edit', liveAsst);
await shot(page, `s5c-${arm}-1-after-edit`);
await page.reload();
await waitText(page, 'Reply to LIMA', 60000);
await sleep(2500);
const rRows = await rows(page); const rAsst = await assistantLines(page);
log('RELOAD rows', rRows);
log('RELOAD assistant', rAsst);
log('live == reload ?', JSON.stringify(liveRows) === JSON.stringify(rRows) && JSON.stringify(liveAsst) === JSON.stringify(rAsst));
await browser.close();
