import sys; sys.path.insert(0,'.')
from card import render
render('PR #12552 round 4: head d1689c16 (merge of main + fence test change)',
 'macOS, JDK 21, Node 24; real `qwen managed-runtime-worker` (dist/cli.js, worker+contract sources identical to head and origin/main)',
['## CI at d1689c16',
 '++ macos-latest / Java 21 (was red), Lint & Static (was red), MariaDB, windows, ubuntu Java 11/17/21: pass',
 '## local',
 '++ module suite 94/94, 0 skipped on JDK 21, 25, 26; checkstyle clean',
 '++ fencedProvisioningReapsTheWorker: lease 100/300/600 ms and 1 min -> 20/20 pass (was F at >=300 ms)',
 '## real worker harness (same as round 3) + new scenario I',
 '++ A1-A5 adopt / re-attest (p50 1.4 ms) / SIGTERM + kill -9 recovery / close()',
 '++ B1 B4 C1 D1 D2 E1 F1 G1 all pass, identical to round 3',
 '!! E2 SIGTERM-ignoring adopted worker survives close()  (deferred R1-23)',
 '++ I1 new: cancel of an in-flight call (#12583 path from main) x PR liveness check',
 '==    alive: transport.cancel x1 | kill -9: 503 runtime_provision_failed, transport.cancel x0',
 '==    execute fails -> UNKNOWN; cancel -> UNKNOWN; release -> 409 busy (existing rule); warm -> gen 2',
 '',
 '== harness totals: 14 pass / 1 fail (E2)'],
 'figs4/fig1-head.png')
render('Fence test coverage: which fenced exit does each test reach?',
 'provisionBinding has two runtime_provision_fenced exits, each calling releaseQuietly; mutant = delete that release; 3 runs each',
['== mutant                               PR tests (d1689c16)        + companion test (+56/-3)',
 '.. X1 exit 1 (renewal lost the claim)   P P P  survives            F F F  provisioningFencedByRenewal...',
 '.. X2 exit 2 (READY CAS refused)        F F F  fencedProvisioning  F F F  fencedProvisioning...',
 '.. X3 both exits                        F F F                      F F F  both tests',
 '',
 '!! The new deterministic test only reaches exit 2; exit 1 lost its (flaky) coverage.',
 '## companion test: renewal fences, and provision waits on a latch until that renewal ran',
 '++ deterministic by construction: 10/10 pass on clean classes; suite 95/95; checkstyle clean'],
 'figs4/fig2-fenced-exits.png')
